#
# Change / create your CHI flit configuration here
#

#
# The CHI Issue.
#   Permitted value: "B", "C", "E.b"
#
ISSUE ?= B

#
# The width of Node ID.
# 	Permitted value: 7 to 11
#
NODEID_WIDTH ?= 7

#
# The width of address of REQ flit, which also effects the SNP flit.
#	Permitted value: 44 to 52
#
REQ_ADDR_WIDTH ?= 48

#
# The width of RSVDC field of REQ flit.
# 	Permitted value: 0 or 4, 8, 12, 16, 24, 32
#
REQ_RSVDC_WIDTH ?= 0

#
# The width of RSVDC field of DAT flit.
#	Permitted value: 0 or 4, 8, 12, 16, 24, 32
#
DAT_RSVDC_WIDTH ?= 0

#
# The width of Data field of DAT flit.
#	Permitted value: 128, 256, 512
#
DATA_WIDTH ?= 256

#
# The presence of DataCheck field of DAT flit.
#	Permitted value: true, false, 0, 1
#
DATACHECK_PRESENT ?= false

#
# The presence of Poison field of DAT flit.
#	Permitted value: true, false, 0, 1
#
POISON_PRESENT ?= false

#
# The presence of MPAM field.
# *Only applicable in Issue E.b*
#	Permitted value: true, false, 0, 1
#
MPAM_PRESENT ?= false
