    ads::CDockManager* dockManager_ = nullptr;
    ads::CDockWidget* topologyDock_ = nullptr;
    ads::CDockWidget* timelineDock_ = nullptr;
    ads::CDockWidget* addressDock_ = nullptr;
    ads::CDockWidget* cacheDock_ = nullptr;
    ads::CDockWidget* latencyDock_ = nullptr;
    ads::CDockWidget* latencyDiffDock_ = nullptr;
    ads::CDockWidget* transactionDock_ = nullptr;
    ads::CDockWidget* clipboardDock_ = nullptr;
    ads::CDockWidget* statisticsDock_ = nullptr;
    FlitTableModel* flitModel_ = nullptr;
    FlitDetailsModel* detailModel_ = nullptr;
    QTableView* flitView_ = nullptr;
    QTableView* detailView_ = nullptr;
    QWidget* traceToolbar_ = nullptr;
    QWidget* traceToolbarContent_ = nullptr;
    QHBoxLayout* traceToolbarSummaryLayout_ = nullptr;
    QHBoxLayout* traceToolbarSearchLayout_ = nullptr;
    QToolButton* traceToolbarFoldButton_ = nullptr;
    QVector<QWidget*> traceToolbarFoldableRows_;
    QVector<QWidget*> traceToolbarFoldableSearchWidgets_;
    QTextBrowser* inspector_ = nullptr;
    QLabel* xactionRowsCaption_ = nullptr;
    QTableWidget* xactionRowsTable_ = nullptr;
    QStackedLayout* statisticsStack_ = nullptr;
    QWidget* statisticsIdleState_ = nullptr;
    QWidget* statisticsLoadingState_ = nullptr;
    QWidget* statisticsResultsState_ = nullptr;
    QLabel* statisticsHintLabel_ = nullptr;
    QLabel* statisticsLoadingLabel_ = nullptr;
    QLabel* statisticsSummaryLabel_ = nullptr;
    QPushButton* statisticsCalculateButton_ = nullptr;
    QPushButton* statisticsCancelButton_ = nullptr;
    QPushButton* statisticsRefreshButton_ = nullptr;
    QProgressBar* statisticsProgressBar_ = nullptr;
    QTableWidget* statisticsOverviewTable_ = nullptr;
    QTableWidget* statisticsOpcodeTable_ = nullptr;
    QLabel* topologySummaryLabel_ = nullptr;
    QTableWidget* topologyTable_ = nullptr;
    QStackedLayout* timelineStack_ = nullptr;
    QStackedLayout* addressStack_ = nullptr;
    QStackedLayout* cacheStack_ = nullptr;
    QStackedLayout* latencyStack_ = nullptr;
    QStackedLayout* transactionStack_ = nullptr;
    TimelineWidget* timelineEmptyWidget_ = nullptr;
    AddressWidget* addressEmptyWidget_ = nullptr;
    CacheWidget* cacheEmptyWidget_ = nullptr;
    LatencyWidget* latencyEmptyWidget_ = nullptr;
    TransactionWidget* transactionEmptyWidget_ = nullptr;
    ClipboardWidget* clipboardWidget_ = nullptr;
    LatencyDiffWidget* latencyDiffWidget_ = nullptr;
    TimelineWidget* timelineWidget_ = nullptr;
    AddressWidget* addressWidget_ = nullptr;
    CacheWidget* cacheWidget_ = nullptr;
    LatencyWidget* latencyWidget_ = nullptr;
    TransactionWidget* transactionWidget_ = nullptr;
    QLineEdit* opcodeFilterEdit_ = nullptr;
    QLineEdit* sourceIdFilterEdit_ = nullptr;
    QLineEdit* targetIdFilterEdit_ = nullptr;
    QLineEdit* txnIdFilterEdit_ = nullptr;
    QLineEdit* dbidFilterEdit_ = nullptr;
    QLineEdit* addressFilterEdit_ = nullptr;
    QToolButton* reqButton_ = nullptr;
    QToolButton* rspButton_ = nullptr;
    QToolButton* datButton_ = nullptr;
    QToolButton* snpButton_ = nullptr;
    QToolButton* txButton_ = nullptr;
    QToolButton* rxButton_ = nullptr;
    QToolButton* deniedFlitsButton_ = nullptr;
    QToolButton* nodeLabelsButton_ = nullptr;
    QToolButton* searchModeButton_ = nullptr;
    QToolButton* searchPreviousButton_ = nullptr;
    QToolButton* searchNextButton_ = nullptr;
    QAction* topologyAction_ = nullptr;
    QAction* xactionIndexAction_ = nullptr;
    QAction* rebuildXactionIndexAction_ = nullptr;
    QAction* clearXactionIndexAction_ = nullptr;
    QAction* xactionDebugAction_ = nullptr;
    QAction* readOnlyModeAction_ = nullptr;
    QAction* saveEditedCopyAction_ = nullptr;
    QAction* latencyDiffAction_ = nullptr;
    QAction* insertBlankFlitAction_ = nullptr;
    QAction* cloneFlitAction_ = nullptr;
    QAction* rebuildDerivedViewsAction_ = nullptr;
    QLabel* searchNavigationLabel_ = nullptr;
    QToolButton* fieldToggleButton_ = nullptr;
    QDialog* fieldToggleDialog_ = nullptr;
    QScrollArea* fieldToggleScrollArea_ = nullptr;
    QWidget* fieldToggleContent_ = nullptr;
    QVBoxLayout* fieldToggleContentLayout_ = nullptr;
    QPushButton* fieldToggleClearButton_ = nullptr;
    QMultiHash<QString, QCheckBox*> fieldToggleCheckboxes_;
    QMultiHash<QString, QToolButton*> fieldIndexButtons_;
    QSet<QString> fieldIndexingFields_;
    QLabel* totalBadge_ = nullptr;
    QLabel* visibleBadge_ = nullptr;
    QLabel* reqBadge_ = nullptr;
    QLabel* rspBadge_ = nullptr;
    QLabel* datBadge_ = nullptr;
    QLabel* snpBadge_ = nullptr;
    QLabel* editStateBadge_ = nullptr;
    QLabel* outdatedViewsBadge_ = nullptr;
    QLabel* filterProgressLabel_ = nullptr;
    QProgressBar* filterProgressBar_ = nullptr;
    QLabel* xactionIndexProgressLabel_ = nullptr;
    QProgressBar* xactionIndexProgressBar_ = nullptr;
    QStackedLayout* traceContentStack_ = nullptr;
    QWidget* traceEmptyState_ = nullptr;
    QPushButton* traceEmptyStateButton_ = nullptr;
    QWidget* optionalFieldSearchRow_ = nullptr;
    QVBoxLayout* optionalFieldSearchLayout_ = nullptr;
    QTabBar* sessionTabBar_ = nullptr;
    QHash<QString, QLineEdit*> optionalFieldFilterEdits_;
    bool rebuildingOptionalFieldSearchRow_ = false;
    bool traceToolbarFolded_ = false;
    bool optionalFieldSearchRowVisibleBeforeToolbarFold_ = false;
    QByteArray defaultLayoutState_;
    struct TraceViewSession {
        quint64 id = 0;
        QString label;
        QString path;
        QString pendingLoadPath;
        std::optional<CLog::Parameters> parameterOverride;
        std::shared_ptr<TraceSession> traceSession;
        FlitTableModel* flitModel = nullptr;
        FlitDetailsModel* detailModel = nullptr;
        TimelineWidget* timelineWidget = nullptr;
        AddressWidget* addressWidget = nullptr;
        CacheWidget* cacheWidget = nullptr;
        LatencyWidget* latencyWidget = nullptr;
        TransactionWidget* transactionWidget = nullptr;
        std::vector<ClipboardEntry> clipboardEntries;
        bool rowBacked = false;
        int selectedLogicalRow = -1;
        int tableVerticalScrollValue = 0;
        QVector<int> tableColumnWidths;
        std::optional<quint16> topologySelectedNodeId;
        QVariantMap timelineViewState;
        QVariantMap addressViewState;
        QVariantMap cacheViewState;
        QVariantMap latencyViewState;
        QVariantMap transactionViewState;
        bool statisticsActive = false;
        bool statisticsComputed = false;
        TraceStatisticsAccumulator statisticsAccumulator;
        std::optional<CLogBTraceMetadata> editableMetadata;
        bool editModeEnabled = false;
        bool dirty = false;
        bool derivedViewsOutdated = false;
        std::shared_ptr<TraceSession> statisticsTraceSessionSource;
        std::vector<FlitRecord> statisticsRowSource;
        TraceStatisticsResult statisticsResult;
        QString statisticsProgressText;
        int statisticsProgressValue = 0;
        int statisticsProgressMaximum = 1000;
        quint64 statisticsGeneration = 0;
        std::size_t statisticsNextBlockIndex = 0;
        std::size_t statisticsNextLocalIndex = 0;
        std::size_t statisticsNextRowIndex = 0;
        std::size_t statisticsChunkRecords = 65536;
        CLogBTraceLoadError statisticsError;
        bool xactionIndexActive = false;
        std::shared_ptr<std::stop_source> xactionIndexStopSource;
        quint64 xactionIndexGeneration = 0;
        QString xactionIndexProgressText;
        std::uint64_t xactionIndexCompletedRecords = 0;
        std::uint64_t xactionIndexTotalRecords = 0;
        QSet<QString> optionalFieldIndexingFields;
    };
    std::vector<std::unique_ptr<TraceViewSession>> traceSessions_;
    quint64 nextTraceSessionId_ = 1;
    quint64 activeTraceSessionId_ = 0;
    bool switchingTraceSession_ = false;
    QString currentTracePath_;
    QString currentTraceLabel_;
    QString pendingTraceLoadPath_;
    QStringList pendingTraceLoadPaths_;
    std::optional<CLog::Parameters> currentTraceParameterOverride_;
    std::shared_ptr<TraceSession> currentTraceSession_;
    std::vector<ClipboardEntry> globalClipboardEntries_;
    std::uint64_t nextClipboardSequence_ = 1;
    QTimer* diagnosticsSnapshotTimer_ = nullptr;
    TraceStatisticsAccumulator statisticsAccumulator_;
    std::shared_ptr<TraceSession> statisticsTraceSessionSource_;
    std::shared_ptr<std::stop_source> xactionIndexStopSource_;
    std::vector<FlitRecord> statisticsRowSource_;
    QString statisticsLoadingFullText_;
    quint64 statisticsGeneration_ = 0;
    quint64 xactionIndexGeneration_ = 0;
    std::size_t statisticsNextBlockIndex_ = 0;
    std::size_t statisticsNextLocalIndex_ = 0;
    std::size_t statisticsNextRowIndex_ = 0;
    std::size_t statisticsChunkRecords_ = 65536;
    CLogBTraceLoadError statisticsError_;
    bool statisticsActive_ = false;
    bool statisticsComputed_ = false;
    bool xactionIndexActive_ = false;
    bool xactionDebugMode_ = false;
