#include "tc_common_initial.hpp"            // IWYU pragma: keep
#include "tcpt_b_initial_dataless.hpp"      // IWYU pragma: keep

#ifdef CHI_ISSUE_E

void TCPtBInitialDataless(
    size_t*                     totalCount,
    size_t*                     errCountFail,
    size_t*                     errCountEnvError,
    std::vector<std::string>*   errList,
    const Xact::Topology&       topo) noexcept
{
    TCPtInitial* tcptInitial = (new TCPtInitial())
        ->TotalCount(totalCount)
        ->ErrCountFail(errCountFail)
        ->ErrCountEnvError(errCountEnvError)
        ->ErrList(errList)
        ->Topology(topo)
        ->Begin();

    tcptInitial
        ->ForkREQ("# TCPt B.1. Initial state of CleanUnique", Opcodes::REQ::CleanUnique)

            ->ForkSilentTransitions("## B.1.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.1.1.1. UC  -> CleanUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.1.1.2. UCE -> CleanUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.1.1.3. UD  -> CleanUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.1.1.4. UDP -> CleanUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.1.1.5. SC  -> CleanUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.1.1.6. SD  -> CleanUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.1.1.7. I   -> CleanUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.1.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.1.2.1. UC  -> CleanUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.1.2.2. UCE -> CleanUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.1.2.3. UD  -> CleanUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.1.2.4. UDP -> CleanUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.1.2.5. SC  -> CleanUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.1.2.6. SD  -> CleanUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.1.2.7. I   -> CleanUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.1.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.1.3.1. UC  -> CleanUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.1.3.2. UCE -> CleanUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.1.3.3. UD  -> CleanUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.1.3.4. UDP -> CleanUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.1.3.5. SC  -> CleanUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.1.3.6. SD  -> CleanUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.1.3.7. I   -> CleanUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.1.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.1.4.1. UC  -> CleanUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.1.4.2. UCE -> CleanUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.1.4.3. UD  -> CleanUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.1.4.4. UDP -> CleanUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.1.4.5. SC  -> CleanUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.1.4.6. SD  -> CleanUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.1.4.7. I   -> CleanUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.1.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.1.5.1. UC  -> CleanUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.1.5.2. UCE -> CleanUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.1.5.3. UD  -> CleanUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.1.5.4. UDP -> CleanUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.1.5.5. SC  -> CleanUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.1.5.6. SD  -> CleanUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.1.5.7. I   -> CleanUnique ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.2. Initial state of MakeUnique", Opcodes::REQ::MakeUnique)

            ->ForkSilentTransitions("## B.2.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.2.1.1. UC  -> MakeUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.2.1.2. UCE -> MakeUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.2.1.3. UD  -> MakeUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.2.1.4. UDP -> MakeUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.2.1.5. SC  -> MakeUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.2.1.6. SD  -> MakeUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.2.1.7. I   -> MakeUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.2.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.2.2.1. UC  -> MakeUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.2.2.2. UCE -> MakeUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.2.2.3. UD  -> MakeUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.2.2.4. UDP -> MakeUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.2.2.5. SC  -> MakeUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.2.2.6. SD  -> MakeUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.2.2.7. I   -> MakeUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.2.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.2.3.1. UC  -> MakeUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.2.3.2. UCE -> MakeUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.2.3.3. UD  -> MakeUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.2.3.4. UDP -> MakeUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.2.3.5. SC  -> MakeUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.2.3.6. SD  -> MakeUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.2.3.7. I   -> MakeUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.2.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.2.4.1. UC  -> MakeUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.2.4.2. UCE -> MakeUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.2.4.3. UD  -> MakeUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.2.4.4. UDP -> MakeUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.2.4.5. SC  -> MakeUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.2.4.6. SD  -> MakeUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.2.4.7. I   -> MakeUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.2.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.2.5.1. UC  -> MakeUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.2.5.2. UCE -> MakeUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.2.5.3. UD  -> MakeUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.2.5.4. UDP -> MakeUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.2.5.5. SC  -> MakeUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.2.5.6. SD  -> MakeUnique ", Xact::CacheStates::SD , true )
                ->Leaf("### B.2.5.7. I   -> MakeUnique ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.3. Initial state of Evict", Opcodes::REQ::Evict)

            ->ForkSilentTransitions("## B.3.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.3.1.1. UC  -> Evict ", Xact::CacheStates::UC , false)
                ->Leaf("### B.3.1.2. UCE -> Evict ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.3.1.3. UD  -> Evict ", Xact::CacheStates::UD , false)
                ->Leaf("### B.3.1.4. UDP -> Evict ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.3.1.5. SC  -> Evict ", Xact::CacheStates::SC , false)
                ->Leaf("### B.3.1.6. SD  -> Evict ", Xact::CacheStates::SD , false)
                ->Leaf("### B.3.1.7. I   -> Evict ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.3.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.3.2.1. UC  -> Evict ", Xact::CacheStates::UC , false)
                ->Leaf("### B.3.2.2. UCE -> Evict ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.3.2.3. UD  -> Evict ", Xact::CacheStates::UD , false)
                ->Leaf("### B.3.2.4. UDP -> Evict ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.3.2.5. SC  -> Evict ", Xact::CacheStates::SC , false)
                ->Leaf("### B.3.2.6. SD  -> Evict ", Xact::CacheStates::SD , false)
                ->Leaf("### B.3.2.7. I   -> Evict ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.3.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.3.3.1. UC  -> Evict ", Xact::CacheStates::UC , true )
                ->Leaf("### B.3.3.2. UCE -> Evict ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.3.3.3. UD  -> Evict ", Xact::CacheStates::UD , false)
                ->Leaf("### B.3.3.4. UDP -> Evict ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.3.3.5. SC  -> Evict ", Xact::CacheStates::SC , true )
                ->Leaf("### B.3.3.6. SD  -> Evict ", Xact::CacheStates::SD , false)
                ->Leaf("### B.3.3.7. I   -> Evict ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.3.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.3.4.1. UC  -> Evict ", Xact::CacheStates::UC , true )
                ->Leaf("### B.3.4.2. UCE -> Evict ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.3.4.3. UD  -> Evict ", Xact::CacheStates::UD , true )
                ->Leaf("### B.3.4.4. UDP -> Evict ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.3.4.5. SC  -> Evict ", Xact::CacheStates::SC , true )
                ->Leaf("### B.3.4.6. SD  -> Evict ", Xact::CacheStates::SD , false)
                ->Leaf("### B.3.4.7. I   -> Evict ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.3.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.3.5.1. UC  -> Evict ", Xact::CacheStates::UC , true )
                ->Leaf("### B.3.5.2. UCE -> Evict ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.3.5.3. UD  -> Evict ", Xact::CacheStates::UD , true )
                ->Leaf("### B.3.5.4. UDP -> Evict ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.3.5.5. SC  -> Evict ", Xact::CacheStates::SC , true )
                ->Leaf("### B.3.5.6. SD  -> Evict ", Xact::CacheStates::SD , false)
                ->Leaf("### B.3.5.7. I   -> Evict ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.4. Initial state of StashOnceUnique", Opcodes::REQ::StashOnceUnique)

            ->ForkSilentTransitions("## B.4.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.4.1.1. UC  -> StashOnceUnique ", Xact::CacheStates::UC , false)
                ->Leaf("### B.4.1.2. UCE -> StashOnceUnique ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.4.1.3. UD  -> StashOnceUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.4.1.4. UDP -> StashOnceUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.4.1.5. SC  -> StashOnceUnique ", Xact::CacheStates::SC , false)
                ->Leaf("### B.4.1.6. SD  -> StashOnceUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.4.1.7. I   -> StashOnceUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.4.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.4.2.1. UC  -> StashOnceUnique ", Xact::CacheStates::UC , false)
                ->Leaf("### B.4.2.2. UCE -> StashOnceUnique ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.4.2.3. UD  -> StashOnceUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.4.2.4. UDP -> StashOnceUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.4.2.5. SC  -> StashOnceUnique ", Xact::CacheStates::SC , false)
                ->Leaf("### B.4.2.6. SD  -> StashOnceUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.4.2.7. I   -> StashOnceUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.4.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.4.3.1. UC  -> StashOnceUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.4.3.2. UCE -> StashOnceUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.4.3.3. UD  -> StashOnceUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.4.3.4. UDP -> StashOnceUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.4.3.5. SC  -> StashOnceUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.4.3.6. SD  -> StashOnceUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.4.3.7. I   -> StashOnceUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.4.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.4.4.1. UC  -> StashOnceUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.4.4.2. UCE -> StashOnceUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.4.4.3. UD  -> StashOnceUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.4.4.4. UDP -> StashOnceUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.4.4.5. SC  -> StashOnceUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.4.4.6. SD  -> StashOnceUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.4.4.7. I   -> StashOnceUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.4.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.4.5.1. UC  -> StashOnceUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.4.5.2. UCE -> StashOnceUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.4.5.3. UD  -> StashOnceUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.4.5.4. UDP -> StashOnceUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.4.5.5. SC  -> StashOnceUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.4.5.6. SD  -> StashOnceUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.4.5.7. I   -> StashOnceUnique ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.5. Initial state of StashOnceSepUnique", Opcodes::REQ::StashOnceSepUnique)

            ->ForkSilentTransitions("## B.5.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.5.1.1. UC  -> StashOnceSepUnique ", Xact::CacheStates::UC , false)
                ->Leaf("### B.5.1.2. UCE -> StashOnceSepUnique ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.5.1.3. UD  -> StashOnceSepUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.5.1.4. UDP -> StashOnceSepUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.5.1.5. SC  -> StashOnceSepUnique ", Xact::CacheStates::SC , false)
                ->Leaf("### B.5.1.6. SD  -> StashOnceSepUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.5.1.7. I   -> StashOnceSepUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.5.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.5.2.1. UC  -> StashOnceSepUnique ", Xact::CacheStates::UC , false)
                ->Leaf("### B.5.2.2. UCE -> StashOnceSepUnique ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.5.2.3. UD  -> StashOnceSepUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.5.2.4. UDP -> StashOnceSepUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.5.2.5. SC  -> StashOnceSepUnique ", Xact::CacheStates::SC , false)
                ->Leaf("### B.5.2.6. SD  -> StashOnceSepUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.5.2.7. I   -> StashOnceSepUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.5.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.5.3.1. UC  -> StashOnceSepUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.5.3.2. UCE -> StashOnceSepUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.5.3.3. UD  -> StashOnceSepUnique ", Xact::CacheStates::UD , false)
                ->Leaf("### B.5.3.4. UDP -> StashOnceSepUnique ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.5.3.5. SC  -> StashOnceSepUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.5.3.6. SD  -> StashOnceSepUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.5.3.7. I   -> StashOnceSepUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.5.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.5.4.1. UC  -> StashOnceSepUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.5.4.2. UCE -> StashOnceSepUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.5.4.3. UD  -> StashOnceSepUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.5.4.4. UDP -> StashOnceSepUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.5.4.5. SC  -> StashOnceSepUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.5.4.6. SD  -> StashOnceSepUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.5.4.7. I   -> StashOnceSepUnique ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.5.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.5.5.1. UC  -> StashOnceSepUnique ", Xact::CacheStates::UC , true )
                ->Leaf("### B.5.5.2. UCE -> StashOnceSepUnique ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.5.5.3. UD  -> StashOnceSepUnique ", Xact::CacheStates::UD , true )
                ->Leaf("### B.5.5.4. UDP -> StashOnceSepUnique ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.5.5.5. SC  -> StashOnceSepUnique ", Xact::CacheStates::SC , true )
                ->Leaf("### B.5.5.6. SD  -> StashOnceSepUnique ", Xact::CacheStates::SD , false)
                ->Leaf("### B.5.5.7. I   -> StashOnceSepUnique ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.6. Initial state of StashOnceShared", Opcodes::REQ::StashOnceShared)

            ->ForkSilentTransitions("## B.6.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.6.1.1. UC  -> StashOnceShared ", Xact::CacheStates::UC , false)
                ->Leaf("### B.6.1.2. UCE -> StashOnceShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.6.1.3. UD  -> StashOnceShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.6.1.4. UDP -> StashOnceShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.6.1.5. SC  -> StashOnceShared ", Xact::CacheStates::SC , false)
                ->Leaf("### B.6.1.6. SD  -> StashOnceShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.6.1.7. I   -> StashOnceShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.6.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.6.2.1. UC  -> StashOnceShared ", Xact::CacheStates::UC , false)
                ->Leaf("### B.6.2.2. UCE -> StashOnceShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.6.2.3. UD  -> StashOnceShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.6.2.4. UDP -> StashOnceShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.6.2.5. SC  -> StashOnceShared ", Xact::CacheStates::SC , false)
                ->Leaf("### B.6.2.6. SD  -> StashOnceShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.6.2.7. I   -> StashOnceShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.6.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.6.3.1. UC  -> StashOnceShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.6.3.2. UCE -> StashOnceShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.6.3.3. UD  -> StashOnceShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.6.3.4. UDP -> StashOnceShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.6.3.5. SC  -> StashOnceShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.6.3.6. SD  -> StashOnceShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.6.3.7. I   -> StashOnceShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.6.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.6.4.1. UC  -> StashOnceShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.6.4.2. UCE -> StashOnceShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.6.4.3. UD  -> StashOnceShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.6.4.4. UDP -> StashOnceShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.6.4.5. SC  -> StashOnceShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.6.4.6. SD  -> StashOnceShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.6.4.7. I   -> StashOnceShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.6.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.6.5.1. UC  -> StashOnceShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.6.5.2. UCE -> StashOnceShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.6.5.3. UD  -> StashOnceShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.6.5.4. UDP -> StashOnceShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.6.5.5. SC  -> StashOnceShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.6.5.6. SD  -> StashOnceShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.6.5.7. I   -> StashOnceShared ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.7. Initial state of StashOnceSepShared", Opcodes::REQ::StashOnceSepShared)

            ->ForkSilentTransitions("## B.7.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.7.1.1. UC  -> StashOnceSepShared ", Xact::CacheStates::UC , false)
                ->Leaf("### B.7.1.2. UCE -> StashOnceSepShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.7.1.3. UD  -> StashOnceSepShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.7.1.4. UDP -> StashOnceSepShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.7.1.5. SC  -> StashOnceSepShared ", Xact::CacheStates::SC , false)
                ->Leaf("### B.7.1.6. SD  -> StashOnceSepShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.7.1.7. I   -> StashOnceSepShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.7.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.7.2.1. UC  -> StashOnceSepShared ", Xact::CacheStates::UC , false)
                ->Leaf("### B.7.2.2. UCE -> StashOnceSepShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.7.2.3. UD  -> StashOnceSepShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.7.2.4. UDP -> StashOnceSepShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.7.2.5. SC  -> StashOnceSepShared ", Xact::CacheStates::SC , false)
                ->Leaf("### B.7.2.6. SD  -> StashOnceSepShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.7.2.7. I   -> StashOnceSepShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.7.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.7.3.1. UC  -> StashOnceSepShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.7.3.2. UCE -> StashOnceSepShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.7.3.3. UD  -> StashOnceSepShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.7.3.4. UDP -> StashOnceSepShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.7.3.5. SC  -> StashOnceSepShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.7.3.6. SD  -> StashOnceSepShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.7.3.7. I   -> StashOnceSepShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.7.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.7.4.1. UC  -> StashOnceSepShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.7.4.2. UCE -> StashOnceSepShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.7.4.3. UD  -> StashOnceSepShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.7.4.4. UDP -> StashOnceSepShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.7.4.5. SC  -> StashOnceSepShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.7.4.6. SD  -> StashOnceSepShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.7.4.7. I   -> StashOnceSepShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.7.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.7.5.1. UC  -> StashOnceSepShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.7.5.2. UCE -> StashOnceSepShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.7.5.3. UD  -> StashOnceSepShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.7.5.4. UDP -> StashOnceSepShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.7.5.5. SC  -> StashOnceSepShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.7.5.6. SD  -> StashOnceSepShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.7.5.7. I   -> StashOnceSepShared ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.8. Initial state of CleanShared", Opcodes::REQ::CleanShared)

            ->ForkSilentTransitions("## B.8.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.8.1.1. UC  -> CleanShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.8.1.2. UCE -> CleanShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.8.1.3. UD  -> CleanShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.8.1.4. UDP -> CleanShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.8.1.5. SC  -> CleanShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.8.1.6. SD  -> CleanShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.8.1.7. I   -> CleanShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.8.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.8.2.1. UC  -> CleanShared ", Xact::CacheStates::UC , true)
                ->Leaf("### B.8.2.2. UCE -> CleanShared ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.8.2.3. UD  -> CleanShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.8.2.4. UDP -> CleanShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.8.2.5. SC  -> CleanShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.8.2.6. SD  -> CleanShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.8.2.7. I   -> CleanShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.8.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.8.3.1. UC  -> CleanShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.8.3.2. UCE -> CleanShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.8.3.3. UD  -> CleanShared ", Xact::CacheStates::UD , false)
                ->Leaf("### B.8.3.4. UDP -> CleanShared ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.8.3.5. SC  -> CleanShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.8.3.6. SD  -> CleanShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.8.3.7. I   -> CleanShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.8.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.8.4.1. UC  -> CleanShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.8.4.2. UCE -> CleanShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.8.4.3. UD  -> CleanShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.8.4.4. UDP -> CleanShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.8.4.5. SC  -> CleanShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.8.4.6. SD  -> CleanShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.8.4.7. I   -> CleanShared ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.8.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.8.5.1. UC  -> CleanShared ", Xact::CacheStates::UC , true )
                ->Leaf("### B.8.5.2. UCE -> CleanShared ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.8.5.3. UD  -> CleanShared ", Xact::CacheStates::UD , true )
                ->Leaf("### B.8.5.4. UDP -> CleanShared ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.8.5.5. SC  -> CleanShared ", Xact::CacheStates::SC , true )
                ->Leaf("### B.8.5.6. SD  -> CleanShared ", Xact::CacheStates::SD , false)
                ->Leaf("### B.8.5.7. I   -> CleanShared ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.9. Initial state of CleanSharedPersist", Opcodes::REQ::CleanSharedPersist)

            ->ForkSilentTransitions("## B.9.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.9.1.1. UC  -> CleanSharedPersist ", Xact::CacheStates::UC , true )
                ->Leaf("### B.9.1.2. UCE -> CleanSharedPersist ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.9.1.3. UD  -> CleanSharedPersist ", Xact::CacheStates::UD , false)
                ->Leaf("### B.9.1.4. UDP -> CleanSharedPersist ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.9.1.5. SC  -> CleanSharedPersist ", Xact::CacheStates::SC , true )
                ->Leaf("### B.9.1.6. SD  -> CleanSharedPersist ", Xact::CacheStates::SD , false)
                ->Leaf("### B.9.1.7. I   -> CleanSharedPersist ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.9.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.9.2.1. UC  -> CleanSharedPersist ", Xact::CacheStates::UC , true)
                ->Leaf("### B.9.2.2. UCE -> CleanSharedPersist ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.9.2.3. UD  -> CleanSharedPersist ", Xact::CacheStates::UD , false)
                ->Leaf("### B.9.2.4. UDP -> CleanSharedPersist ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.9.2.5. SC  -> CleanSharedPersist ", Xact::CacheStates::SC , true )
                ->Leaf("### B.9.2.6. SD  -> CleanSharedPersist ", Xact::CacheStates::SD , false)
                ->Leaf("### B.9.2.7. I   -> CleanSharedPersist ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.9.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.9.3.1. UC  -> CleanSharedPersist ", Xact::CacheStates::UC , true )
                ->Leaf("### B.9.3.2. UCE -> CleanSharedPersist ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.9.3.3. UD  -> CleanSharedPersist ", Xact::CacheStates::UD , false)
                ->Leaf("### B.9.3.4. UDP -> CleanSharedPersist ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.9.3.5. SC  -> CleanSharedPersist ", Xact::CacheStates::SC , true )
                ->Leaf("### B.9.3.6. SD  -> CleanSharedPersist ", Xact::CacheStates::SD , false)
                ->Leaf("### B.9.3.7. I   -> CleanSharedPersist ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.9.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.9.4.1. UC  -> CleanSharedPersist ", Xact::CacheStates::UC , true )
                ->Leaf("### B.9.4.2. UCE -> CleanSharedPersist ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.9.4.3. UD  -> CleanSharedPersist ", Xact::CacheStates::UD , true )
                ->Leaf("### B.9.4.4. UDP -> CleanSharedPersist ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.9.4.5. SC  -> CleanSharedPersist ", Xact::CacheStates::SC , true )
                ->Leaf("### B.9.4.6. SD  -> CleanSharedPersist ", Xact::CacheStates::SD , false)
                ->Leaf("### B.9.4.7. I   -> CleanSharedPersist ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.9.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.9.5.1. UC  -> CleanSharedPersist ", Xact::CacheStates::UC , true )
                ->Leaf("### B.9.5.2. UCE -> CleanSharedPersist ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.9.5.3. UD  -> CleanSharedPersist ", Xact::CacheStates::UD , true )
                ->Leaf("### B.9.5.4. UDP -> CleanSharedPersist ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.9.5.5. SC  -> CleanSharedPersist ", Xact::CacheStates::SC , true )
                ->Leaf("### B.9.5.6. SD  -> CleanSharedPersist ", Xact::CacheStates::SD , false)
                ->Leaf("### B.9.5.7. I   -> CleanSharedPersist ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.10. Initial state of CleanSharedPersistSep", Opcodes::REQ::CleanSharedPersistSep)

            ->ForkSilentTransitions("## B.10.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.10.1.1. UC  -> CleanSharedPersistSep ", Xact::CacheStates::UC , true )
                ->Leaf("### B.10.1.2. UCE -> CleanSharedPersistSep ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.10.1.3. UD  -> CleanSharedPersistSep ", Xact::CacheStates::UD , false)
                ->Leaf("### B.10.1.4. UDP -> CleanSharedPersistSep ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.10.1.5. SC  -> CleanSharedPersistSep ", Xact::CacheStates::SC , true )
                ->Leaf("### B.10.1.6. SD  -> CleanSharedPersistSep ", Xact::CacheStates::SD , false)
                ->Leaf("### B.10.1.7. I   -> CleanSharedPersistSep ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.10.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.10.2.1. UC  -> CleanSharedPersistSep ", Xact::CacheStates::UC , true)
                ->Leaf("### B.10.2.2. UCE -> CleanSharedPersistSep ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.10.2.3. UD  -> CleanSharedPersistSep ", Xact::CacheStates::UD , false)
                ->Leaf("### B.10.2.4. UDP -> CleanSharedPersistSep ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.10.2.5. SC  -> CleanSharedPersistSep ", Xact::CacheStates::SC , true )
                ->Leaf("### B.10.2.6. SD  -> CleanSharedPersistSep ", Xact::CacheStates::SD , false)
                ->Leaf("### B.10.2.7. I   -> CleanSharedPersistSep ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.10.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.10.3.1. UC  -> CleanSharedPersistSep ", Xact::CacheStates::UC , true )
                ->Leaf("### B.10.3.2. UCE -> CleanSharedPersistSep ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.10.3.3. UD  -> CleanSharedPersistSep ", Xact::CacheStates::UD , false)
                ->Leaf("### B.10.3.4. UDP -> CleanSharedPersistSep ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.10.3.5. SC  -> CleanSharedPersistSep ", Xact::CacheStates::SC , true )
                ->Leaf("### B.10.3.6. SD  -> CleanSharedPersistSep ", Xact::CacheStates::SD , false)
                ->Leaf("### B.10.3.7. I   -> CleanSharedPersistSep ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.10.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.10.4.1. UC  -> CleanSharedPersistSep ", Xact::CacheStates::UC , true )
                ->Leaf("### B.10.4.2. UCE -> CleanSharedPersistSep ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.10.4.3. UD  -> CleanSharedPersistSep ", Xact::CacheStates::UD , true )
                ->Leaf("### B.10.4.4. UDP -> CleanSharedPersistSep ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.10.4.5. SC  -> CleanSharedPersistSep ", Xact::CacheStates::SC , true )
                ->Leaf("### B.10.4.6. SD  -> CleanSharedPersistSep ", Xact::CacheStates::SD , false)
                ->Leaf("### B.10.4.7. I   -> CleanSharedPersistSep ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.10.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.10.5.1. UC  -> CleanSharedPersistSep ", Xact::CacheStates::UC , true )
                ->Leaf("### B.10.5.2. UCE -> CleanSharedPersistSep ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.10.5.3. UD  -> CleanSharedPersistSep ", Xact::CacheStates::UD , true )
                ->Leaf("### B.10.5.4. UDP -> CleanSharedPersistSep ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.10.5.5. SC  -> CleanSharedPersistSep ", Xact::CacheStates::SC , true )
                ->Leaf("### B.10.5.6. SD  -> CleanSharedPersistSep ", Xact::CacheStates::SD , false)
                ->Leaf("### B.10.5.7. I   -> CleanSharedPersistSep ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.11. Initial state of CleanInvalid", Opcodes::REQ::CleanInvalid)

            ->ForkSilentTransitions("## B.11.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.11.1.1. UC  -> CleanInvalid ", Xact::CacheStates::UC , false)
                ->Leaf("### B.11.1.2. UCE -> CleanInvalid ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.11.1.3. UD  -> CleanInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.11.1.4. UDP -> CleanInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.11.1.5. SC  -> CleanInvalid ", Xact::CacheStates::SC , false)
                ->Leaf("### B.11.1.6. SD  -> CleanInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.11.1.7. I   -> CleanInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.11.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.11.2.1. UC  -> CleanInvalid ", Xact::CacheStates::UC , false)
                ->Leaf("### B.11.2.2. UCE -> CleanInvalid ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.11.2.3. UD  -> CleanInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.11.2.4. UDP -> CleanInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.11.2.5. SC  -> CleanInvalid ", Xact::CacheStates::SC , false)
                ->Leaf("### B.11.2.6. SD  -> CleanInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.11.2.7. I   -> CleanInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.11.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.11.3.1. UC  -> CleanInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.11.3.2. UCE -> CleanInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.11.3.3. UD  -> CleanInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.11.3.4. UDP -> CleanInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.11.3.5. SC  -> CleanInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.11.3.6. SD  -> CleanInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.11.3.7. I   -> CleanInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.11.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.11.4.1. UC  -> CleanInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.11.4.2. UCE -> CleanInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.11.4.3. UD  -> CleanInvalid ", Xact::CacheStates::UD , true )
                ->Leaf("### B.11.4.4. UDP -> CleanInvalid ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.11.4.5. SC  -> CleanInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.11.4.6. SD  -> CleanInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.11.4.7. I   -> CleanInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.11.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.11.5.1. UC  -> CleanInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.11.5.2. UCE -> CleanInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.11.5.3. UD  -> CleanInvalid ", Xact::CacheStates::UD , true )
                ->Leaf("### B.11.5.4. UDP -> CleanInvalid ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.11.5.5. SC  -> CleanInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.11.5.6. SD  -> CleanInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.11.5.7. I   -> CleanInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt B.12. Initial state of MakeInvalid", Opcodes::REQ::MakeInvalid)

            ->ForkSilentTransitions("## B.12.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### B.12.1.1. UC  -> MakeInvalid ", Xact::CacheStates::UC , false)
                ->Leaf("### B.12.1.2. UCE -> MakeInvalid ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.12.1.3. UD  -> MakeInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.12.1.4. UDP -> MakeInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.12.1.5. SC  -> MakeInvalid ", Xact::CacheStates::SC , false)
                ->Leaf("### B.12.1.6. SD  -> MakeInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.12.1.7. I   -> MakeInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.12.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### B.12.2.1. UC  -> MakeInvalid ", Xact::CacheStates::UC , false)
                ->Leaf("### B.12.2.2. UCE -> MakeInvalid ", Xact::CacheStates::UCE, false)
                ->Leaf("### B.12.2.3. UD  -> MakeInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.12.2.4. UDP -> MakeInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.12.2.5. SC  -> MakeInvalid ", Xact::CacheStates::SC , false)
                ->Leaf("### B.12.2.6. SD  -> MakeInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.12.2.7. I   -> MakeInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.12.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### B.12.3.1. UC  -> MakeInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.12.3.2. UCE -> MakeInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.12.3.3. UD  -> MakeInvalid ", Xact::CacheStates::UD , false)
                ->Leaf("### B.12.3.4. UDP -> MakeInvalid ", Xact::CacheStates::UDP, false)
                ->Leaf("### B.12.3.5. SC  -> MakeInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.12.3.6. SD  -> MakeInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.12.3.7. I   -> MakeInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.12.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### B.12.4.1. UC  -> MakeInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.12.4.2. UCE -> MakeInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.12.4.3. UD  -> MakeInvalid ", Xact::CacheStates::UD , true )
                ->Leaf("### B.12.4.4. UDP -> MakeInvalid ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.12.4.5. SC  -> MakeInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.12.4.6. SD  -> MakeInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.12.4.7. I   -> MakeInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## B.12.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### B.12.5.1. UC  -> MakeInvalid ", Xact::CacheStates::UC , true )
                ->Leaf("### B.12.5.2. UCE -> MakeInvalid ", Xact::CacheStates::UCE, true )
                ->Leaf("### B.12.5.3. UD  -> MakeInvalid ", Xact::CacheStates::UD , true )
                ->Leaf("### B.12.5.4. UDP -> MakeInvalid ", Xact::CacheStates::UDP, true )
                ->Leaf("### B.12.5.5. SC  -> MakeInvalid ", Xact::CacheStates::SC , true )
                ->Leaf("### B.12.5.6. SD  -> MakeInvalid ", Xact::CacheStates::SD , false)
                ->Leaf("### B.12.5.7. I   -> MakeInvalid ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial->End();
    tcptInitial = nullptr;
}


#endif
