#include "tc_common_resp.hpp"           // IWYU pragma: keep
#include "tcpt_e_resp_read.hpp"         // IWYU pragma: keep

#ifdef CHI_ISSUE_E

void TCPtERespRead(
    size_t*                     totalCount,
    size_t*                     errCountFail,
    size_t*                     errCountEnvError,
    std::vector<std::string>*   errList,
    const Xact::Topology&       topo) noexcept
{
    TCPtResp* tcptResp = (new TCPtResp())
        ->TotalCount(totalCount)
        ->ErrCountFail(errCountFail)
        ->ErrCountEnvError(errCountEnvError)
        ->ErrList(errList)
        ->Topology(topo)
        ->Begin();

    tcptResp
        ->ForkREQ("# TCPt E.1. Response of ReadNoSnp", Opcodes::REQ::ReadNoSnp)
            
            ->TestAndForkInitial("## E.1.1. I   -> ReadNoSnp ", Xact::CacheStates::I)
                ->ForkCompData("### E.1.1.1. I   -> ReadNoSnp -> CompData")
                    ->LeafRepeat("#### E.1.1.1.1. I   -> ReadNoSnp -> CompData_I     -> I ", Resp::CompData_I       , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.1.1.1.2. I   -> ReadNoSnp -> CompData_UC    -> I ", Resp::CompData_UC      , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.1.1.1.3. I   -> ReadNoSnp -> CompData_SC         ", Resp::CompData_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.1.1.1.4. I   -> ReadNoSnp -> CompData_UD_PD      ", Resp::CompData_UD_PD   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.1.1.1.5. I   -> ReadNoSnp -> CompData_SD_PD      ", Resp::CompData_SD_PD   , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.1.1.2. I   -> ReadNoSnp -> DataSepResp ")
                    ->LeafRepeat("#### E.1.1.2.1. I   -> ReadNoSnp -> DataSepResp_I     -> I ", Resp::DataSepResp_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.1.1.2.2. I   -> ReadNoSnp -> DataSepResp_UC    -> I ", Resp::DataSepResp_UC    , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.1.1.2.3. I   -> ReadNoSnp -> DataSepResp_SC    -> I ", Resp::DataSepResp_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.1.1.2.4. I   -> ReadNoSnp -> DataSepResp_UD_PD -> I ", Resp::DataSepResp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.2. Response of ReadOnce", Opcodes::REQ::ReadOnce)

            ->TestAndForkInitial("## E.2.1. I   -> ReadOnce", Xact::CacheStates::I)
                ->ForkCompData("### E.2.1.1. I   -> ReadOnce -> CompData")
                    ->LeafRepeat("#### E.2.1.1.1. I   -> ReadOnce -> CompData_I     -> I ", Resp::CompData_I       , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.2.1.1.2. I   -> ReadOnce -> CompData_UC    -> I ", Resp::CompData_UC      , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.2.1.1.3. I   -> ReadOnce -> CompData_SC         ", Resp::CompData_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.2.1.1.4. I   -> ReadOnce -> CompData_UD_PD      ", Resp::CompData_UD_PD   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.2.1.1.5. I   -> ReadOnce -> CompData_SD_PD      ", Resp::CompData_SD_PD   , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.2.1.2. I   -> ReadOnce -> DataSepResp ")
                    ->LeafRepeat("#### E.2.1.2.1. I   -> ReadOnce -> DataSepResp_I     -> I ", Resp::DataSepResp_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.2.1.2.2. I   -> ReadOnce -> DataSepResp_UC    -> I ", Resp::DataSepResp_UC    , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.2.1.2.3. I   -> ReadOnce -> DataSepResp_SC    -> I ", Resp::DataSepResp_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.2.1.2.4. I   -> ReadOnce -> DataSepResp_UD_PD -> I ", Resp::DataSepResp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.3. Response of ReadOnceCleanInvalid", Opcodes::REQ::ReadOnceCleanInvalid)

            ->TestAndForkInitial("## E.3.1. I     -> ReadOnceCleanInvalid", Xact::CacheStates::I)
                ->ForkCompData("### E.3.1.1. I     -> ReadOnceCleanInvalid -> CompData")
                    ->LeafRepeat("#### E.3.1.1.1. I   -> ReadOnceCleanInvalid -> CompData_I     -> I ", Resp::CompData_I       , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.3.1.1.2. I   -> ReadOnceCleanInvalid -> CompData_UC    -> I ", Resp::CompData_UC      , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.3.1.1.3. I   -> ReadOnceCleanInvalid -> CompData_SC         ", Resp::CompData_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.3.1.1.4. I   -> ReadOnceCleanInvalid -> CompData_UD_PD      ", Resp::CompData_UD_PD   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.3.1.1.5. I   -> ReadOnceCleanInvalid -> CompData_SD_PD      ", Resp::CompData_SD_PD   , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.3.1.2. I   -> ReadOnceCleanInvalid -> DataSepResp ")
                    ->LeafRepeat("#### E.3.1.2.1. I   -> ReadOnceCleanInvalid -> DataSepResp_I     -> I ", Resp::DataSepResp_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.3.1.2.2. I   -> ReadOnceCleanInvalid -> DataSepResp_UC    -> I ", Resp::DataSepResp_UC    , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.3.1.2.3. I   -> ReadOnceCleanInvalid -> DataSepResp_SC    -> I ", Resp::DataSepResp_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.3.1.2.4. I   -> ReadOnceCleanInvalid -> DataSepResp_UD_PD -> I ", Resp::DataSepResp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.4. Response of ReadOnceMakeInvalid", Opcodes::REQ::ReadOnceMakeInvalid)

            ->TestAndForkInitial("## E.4.1. I     -> ReadOnceMakeInvalid", Xact::CacheStates::I)
                ->ForkCompData("### E.4.1.1. I     -> ReadOnceMakeInvalid -> CompData")
                    ->LeafRepeat("#### E.4.1.1.1. I   -> ReadOnceMakeInvalid -> CompData_I     -> I ", Resp::CompData_I       , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.4.1.1.2. I   -> ReadOnceMakeInvalid -> CompData_UC    -> I ", Resp::CompData_UC      , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.4.1.1.3. I   -> ReadOnceMakeInvalid -> CompData_SC         ", Resp::CompData_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.4.1.1.4. I   -> ReadOnceMakeInvalid -> CompData_UD_PD      ", Resp::CompData_UD_PD   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.4.1.1.5. I   -> ReadOnceMakeInvalid -> CompData_SD_PD      ", Resp::CompData_SD_PD   , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.4.1.2. I   -> ReadOnceMakeInvalid -> DataSepResp ")
                    ->LeafRepeat("#### E.4.1.2.1. I   -> ReadOnceMakeInvalid -> DataSepResp_I     -> I ", Resp::DataSepResp_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.4.1.2.2. I   -> ReadOnceMakeInvalid -> DataSepResp_UC    -> I ", Resp::DataSepResp_UC    , Xact::CacheStates::I      , true )
                    ->LeafRepeat("#### E.4.1.2.3. I   -> ReadOnceMakeInvalid -> DataSepResp_SC    -> I ", Resp::DataSepResp_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.4.1.2.4. I   -> ReadOnceMakeInvalid -> DataSepResp_UD_PD -> I ", Resp::DataSepResp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.5. Response of ReadClean", Opcodes::REQ::ReadClean)

            ->TestAndForkInitial("## E.5.1. I   -> ReadClean", Xact::CacheStates::I)
                ->ForkCompData("### E.5.1.1. I   -> ReadClean -> CompData")
                    ->LeafRepeat("#### E.5.1.1.1. I   -> ReadClean -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.1.1.2. I   -> ReadClean -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.1.1.3. I   -> ReadClean -> CompData_SC    -> SC ", Resp::CompData_SC   , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.5.1.1.4. I   -> ReadClean -> CompData_UD_PD       ", Resp::CompData_UD_PD, Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.1.1.5. I   -> ReadClean -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.5.1.2. I   -> ReadClean -> DataSepResp")
                    ->LeafRepeat("#### E.5.1.2.1. I   -> ReadClean -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.1.2.2. I   -> ReadClean -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.1.2.3. I   -> ReadClean -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC     , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.5.1.2.4. I   -> ReadClean -> DataSepResp_UD_PD       ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.5.2. UCE -> ReadClean", Xact::CacheStates::UCE)
                ->ForkCompData("### E.5.2.1. UCE -> ReadClean -> CompData")
                    ->LeafRepeat("#### E.5.2.1.1. UCE -> ReadClean -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.2.1.2. UCE -> ReadClean -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.2.1.3. UCE -> ReadClean -> CompData_SC    -> UC ", Resp::CompData_SC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.2.1.4. UCE -> ReadClean -> CompData_UD_PD       ", Resp::CompData_UD_PD, Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.2.1.5. UCE -> ReadClean -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.5.2.2. UCE -> ReadClean -> DataSepResp")
                    ->LeafRepeat("#### E.5.1.2.1. UCE -> ReadClean -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.5.1.2.2. UCE -> ReadClean -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.1.2.3. UCE -> ReadClean -> DataSepResp_SC    -> UC ", Resp::DataSepResp_SC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.5.1.2.4. UCE -> ReadClean -> DataSepResp_UD_PD       ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.6. Response of ReadNotSharedDirty", Opcodes::REQ::ReadNotSharedDirty)

            ->TestAndForkInitial("## E.6.1. I   -> ReadNotSharedDirty", Xact::CacheStates::I)
                ->ForkCompData("### E.6.1.1. I   -> ReadNotSharedDirty -> CompData")
                    ->LeafRepeat("#### E.6.1.1.1. I   -> ReadNotSharedDirty -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.6.1.1.2. I   -> ReadNotSharedDirty -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.6.1.1.3. I   -> ReadNotSharedDirty -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.6.1.1.4. I   -> ReadNotSharedDirty -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.6.1.1.5. I   -> ReadNotSharedDirty -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.6.1.2. I   -> ReadNotSharedDirty -> DataSepResp")
                    ->LeafRepeat("#### E.6.1.2.1. I   -> ReadNotSharedDirty -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.6.1.2.2. I   -> ReadNotSharedDirty -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.6.1.2.3. I   -> ReadNotSharedDirty -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.6.1.2.4. I   -> ReadNotSharedDirty -> DataSepResp_UD_PD       ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.6.2. UCE -> ReadNotSharedDirty", Xact::CacheStates::UCE)
                ->ForkCompData("### E.6.2.1. UCE -> ReadNotSharedDirty -> CompData")
                    ->LeafRepeat("#### E.6.2.1.1. UCE -> ReadNotSharedDirty -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.6.2.1.2. UCE -> ReadNotSharedDirty -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.6.2.1.3. UCE -> ReadNotSharedDirty -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.6.2.1.4. UCE -> ReadNotSharedDirty -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.6.2.1.5. UCE -> ReadNotSharedDirty -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.6.2.2. UCE -> ReadNotSharedDirty -> DataSepResp")
                    ->LeafRepeat("#### E.6.2.2.1. UCE -> ReadNotSharedDirty -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.6.2.2.2. UCE -> ReadNotSharedDirty -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.6.2.2.3. UCE -> ReadNotSharedDirty -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.6.2.2.4. UCE -> ReadNotSharedDirty -> DataSepResp_UD_PD       ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.7. Response of ReadShared", Opcodes::REQ::ReadShared)

            ->TestAndForkInitial("## E.7.1. I   -> ReadShared", Xact::CacheStates::I)
                ->ForkCompData("### E.7.1.1. I   -> ReadShared -> CompData")
                    ->LeafRepeat("#### E.7.1.1.1. I   -> ReadShared -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.7.1.1.2. I   -> ReadShared -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.7.1.1.3. I   -> ReadShared -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.7.1.1.4. I   -> ReadShared -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.7.1.1.5. I   -> ReadShared -> CompData_SD_PD -> SD ", Resp::CompData_SD_PD , Xact::CacheStates::SD     , true )
                ->Rest()
                ->ForkDataSepResp("### E.7.1.2. I   -> ReadShared -> DataSepResp")
                    ->LeafRepeat("#### E.7.1.2.1. I   -> ReadShared -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.7.1.2.2. I   -> ReadShared -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.7.1.2.3. I   -> ReadShared -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.7.1.2.4. I   -> ReadShared -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.7.2. UCE -> ReadShared", Xact::CacheStates::UCE)
                ->ForkCompData("### E.7.2.1. UCE -> ReadShared -> CompData")
                    ->LeafRepeat("#### E.7.2.1.1. UCE -> ReadShared -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.7.2.1.2. UCE -> ReadShared -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.7.2.1.3. UCE -> ReadShared -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.7.2.1.4. UCE -> ReadShared -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.7.2.1.5. UCE -> ReadShared -> CompData_SD_PD -> SD ", Resp::CompData_SD_PD , Xact::CacheStates::SD     , true )
                ->Rest()
                ->ForkDataSepResp("### E.7.1.2. UCE -> ReadShared -> DataSepResp")
                    ->LeafRepeat("#### E.7.2.2.1. UCE -> ReadShared -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.7.2.2.2. UCE -> ReadShared -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.7.2.2.3. UCE -> ReadShared -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.7.2.2.4. UCE -> ReadShared -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.8. Response of ReadUnique", Opcodes::REQ::ReadUnique)

            ->TestAndForkInitial("## E.8.1. I   -> ReadUnique", Xact::CacheStates::I)
                ->ForkCompData("### E.8.1.1. I   -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.1.1.1. I   -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.1.1.2. I   -> ReadUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.1.1.3. I   -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.1.1.4. I   -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.1.1.5. I   -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.1.2. I   -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.1.2.1. I   -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.1.2.2. I   -> ReadUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.1.2.3. I   -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.1.2.4. I   -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.2. SC  -> ReadUnique", Xact::CacheStates::SC)
                ->ForkCompData("### E.8.2.1. SC  -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.2.1.1. SC  -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.2.1.2. SC  -> ReadUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.2.1.3. SC  -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.2.1.4. SC  -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.2.1.5. SC  -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.2.2. SC  -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.2.2.1. SC  -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.2.2.2. SC  -> ReadUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.2.2.3. SC  -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.2.2.4. SC  -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.3. UC  -> ReadUnique", Xact::CacheStates::UC)
                ->ForkCompData("### E.8.3.1. UC  -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.3.1.1. UC  -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.3.1.2. UC  -> ReadUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.3.1.3. UC  -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.3.1.4. UC  -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.3.1.5. UC  -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.3.2. UC  -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.3.2.1. UC  -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.3.2.2. UC  -> ReadUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.3.2.3. UC  -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.3.2.4. UC  -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.4. UCE -> ReadUnique", Xact::CacheStates::UCE)\
                ->ForkCompData("### E.8.4.1. UCE -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.4.1.1. UCE -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.4.1.2. UCE -> ReadUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.4.1.3. UCE -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.4.1.4. UCE -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.4.1.5. UCE -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.4.2. UCE -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.4.2.1. UCE -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.4.2.2. UCE -> ReadUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.8.4.2.3. UCE -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.4.2.4. UCE -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.5. SD  -> ReadUnique", Xact::CacheStates::SD)
                ->ForkCompData("### E.8.5.1. SD  -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.5.1.1. SD  -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.5.1.2. SD  -> ReadUnique -> CompData_UC    -> UD ", Resp::CompData_UC    , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.5.1.3. SD  -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.5.1.4. SD  -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.5.1.5. SD  -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.5.2. SD  -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.5.2.1. SD  -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.5.2.2. SD  -> ReadUnique -> DataSepResp_UC    -> UD ", Resp::DataSepResp_UC      , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.5.2.3. SD  -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.5.2.4. SD  -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.6. UD  -> ReadUnique", Xact::CacheStates::UD)
                ->ForkCompData("### E.8.6.1. UD  -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.6.1.1. UD  -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.6.1.2. UD  -> ReadUnique -> CompData_UC    -> UD ", Resp::CompData_UC    , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.6.1.3. UD  -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.6.1.4. UD  -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.6.1.5. UD  -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.6.2. UD  -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.6.2.1. UD  -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.6.2.2. UD  -> ReadUnique -> DataSepResp_UC    -> UD ", Resp::DataSepResp_UC      , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.6.2.3. UD  -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.6.2.4. UD  -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.8.7. UDP -> ReadUnique", Xact::CacheStates::UDP)
                ->ForkCompData("### E.8.7.1. UDP -> ReadUnique -> CompData")
                    ->LeafRepeat("#### E.8.7.1.1. UDP -> ReadUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.7.1.2. UDP -> ReadUnique -> CompData_UC    -> UD ", Resp::CompData_UC    , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.7.1.3. UDP -> ReadUnique -> CompData_SC          ", Resp::CompData_SC    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.7.1.4. UDP -> ReadUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.7.1.5. UDP -> ReadUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.8.7.2. UDP -> ReadUnique -> DataSepResp")
                    ->LeafRepeat("#### E.8.7.2.1. UDP -> ReadUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.7.2.2. UDP -> ReadUnique -> DataSepResp_UC    -> UD ", Resp::DataSepResp_UC      , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.8.7.2.3. UDP -> ReadUnique -> DataSepResp_SC          ", Resp::DataSepResp_SC      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.8.7.2.4. UDP -> ReadUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.9. Response of ReadPreferUnique", Opcodes::REQ::ReadPreferUnique)

            ->TestAndForkInitial("## E.9.1. I   -> ReadPreferUnique", Xact::CacheStates::I)
                ->ForkCompData("### E.9.1.1. I   -> ReadPreferUnique -> CompData")
                    ->LeafRepeat("#### E.9.1.1.1. I   -> ReadPreferUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.1.1.2. I   -> ReadPreferUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.9.1.1.3. I   -> ReadPreferUnique -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.9.1.1.4. I   -> ReadPreferUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.9.1.1.5. I   -> ReadPreferUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.9.1.2. I   -> ReadPreferUnique -> DataSepResp")
                    ->LeafRepeat("#### E.9.1.2.1. I   -> ReadPreferUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.1.2.2. I   -> ReadPreferUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.9.1.2.3. I   -> ReadPreferUnique -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.9.1.2.4. I   -> ReadPreferUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.9.2. SC  -> ReadPreferUnique", Xact::CacheStates::SC)
                ->ForkCompData("### E.9.2.1. SC  -> ReadPreferUnique -> CompData")
                    ->LeafRepeat("#### E.9.2.1.1. SC  -> ReadPreferUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.2.1.2. SC  -> ReadPreferUnique -> CompData_UC    -> UC ", Resp::CompData_UC    , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.9.2.1.3. SC  -> ReadPreferUnique -> CompData_SC    -> SC ", Resp::CompData_SC    , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.9.2.1.4. SC  -> ReadPreferUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.9.2.1.5. SC  -> ReadPreferUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.9.2.2. SC  -> ReadPreferUnique -> DataSepResp")
                    ->LeafRepeat("#### E.9.2.2.1. SC  -> ReadPreferUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.2.2.2. SC  -> ReadPreferUnique -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC      , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.9.2.2.3. SC  -> ReadPreferUnique -> DataSepResp_SC    -> SC ", Resp::DataSepResp_SC      , Xact::CacheStates::SC     , true )
                    ->LeafRepeat("#### E.9.2.2.4. SC  -> ReadPreferUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndForkInitial("## E.9.3. SD  -> ReadPreferUnique", Xact::CacheStates::SD)
                ->ForkCompData("### E.9.3.1. SD  -> ReadPreferUnique -> CompData")
                    ->LeafRepeat("#### E.9.3.1.1. SD  -> ReadPreferUnique -> CompData_I           ", Resp::CompData_I     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.3.1.2. SD  -> ReadPreferUnique -> CompData_UC    -> UD ", Resp::CompData_UC    , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.9.3.1.3. SD  -> ReadPreferUnique -> CompData_SC    -> SD ", Resp::CompData_SC    , Xact::CacheStates::SD     , true )
                    ->LeafRepeat("#### E.9.3.1.4. SD  -> ReadPreferUnique -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.9.3.1.5. SD  -> ReadPreferUnique -> CompData_SD_PD       ", Resp::CompData_SD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.9.3.2. SD  -> ReadPreferUnique -> DataSepResp")
                    ->LeafRepeat("#### E.9.3.2.1. SD  -> ReadPreferUnique -> DataSepResp_I           ", Resp::DataSepResp_I       , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.9.3.2.2. SD  -> ReadPreferUnique -> DataSepResp_UC    -> UD ", Resp::DataSepResp_UC      , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.9.3.2.3. SD  -> ReadPreferUnique -> DataSepResp_SC    -> SD ", Resp::DataSepResp_SC      , Xact::CacheStates::SD     , true )
                    ->LeafRepeat("#### E.9.3.2.4. SD  -> ReadPreferUnique -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD   , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt E.10. Response of MakeReadUnique", Opcodes::REQ::MakeReadUnique)

            ->TestAndLeafTransfer("## E.10.1. SD  -> MakeReadUnique -> UC  ", Xact::CacheStates::SD   , Xact::CacheStates::UC     , false)
            ->TestAndLeafTransfer("## E.10.2. SD  -> MakeReadUnique -> UCE ", Xact::CacheStates::SD   , Xact::CacheStates::UCE    , false)
            ->TestAndLeafTransfer("## E.10.3. SD  -> MakeReadUnique -> UD  ", Xact::CacheStates::SD   , Xact::CacheStates::UD     , false)
            ->TestAndLeafTransfer("## E.10.4. SD  -> MakeReadUnique -> UDP ", Xact::CacheStates::SD   , Xact::CacheStates::UDP    , false)
            ->TestAndForkTransfer("## E.10.5. SD  -> MakeReadUnique -> SC  ", Xact::CacheStates::SD, Xact::CacheStates::SC)
                ->ForkComp("### E.10.5.1. SD  -> MakeReadUnique -> SC  -> Comp")
                    ->Leaf("#### E.10.5.1.1. SD  -> MakeReadUnique -> SC  -> Comp_I           ", Resp::Comp_I     , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.5.1.2. SD  -> MakeReadUnique -> SC  -> Comp_UC    -> UC ", Resp::Comp_UC    , Xact::CacheStates::UC     , true )
                    ->Leaf("#### E.10.5.1.3. SD  -> MakeReadUnique -> SC  -> Comp_SC          ", Resp::Comp_SC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.5.1.4. SD  -> MakeReadUnique -> SC  -> Comp_UD_PD -> UD ", Resp::Comp_UD_PD , Xact::CacheStates::UD     , true )
                ->Rest()
                ->ForkCompData("### E.10.5.2. SD  -> MakeReadUnique -> SC  -> CompData")
                    ->LeafRepeat("#### E.10.5.2.1. SD  -> MakeReadUnique -> SC  -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.5.2.2. SD  -> MakeReadUnique -> SC  -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.5.2.3. SD  -> MakeReadUnique -> SC  -> CompData_SC          ", Resp::CompData_SC   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.5.2.4. SD  -> MakeReadUnique -> SC  -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD, Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.5.2.5. SD  -> MakeReadUnique -> SC  -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.10.5.3. SD  -> MakeReadUnique -> SC  -> DataSepResp")
                    ->LeafRepeat("#### E.10.5.3.1. SD  -> MakeReadUnique -> SC  -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.5.3.2. SD  -> MakeReadUnique -> SC  -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.5.3.3. SD  -> MakeReadUnique -> SC  -> DataSepResp_SC          ", Resp::DataSepResp_SC     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.5.3.4. SD  -> MakeReadUnique -> SC  -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()
            ->TestAndForkTransfer("## E.10.6. SD  -> MakeReadUnique -> SD  ", Xact::CacheStates::SD, Xact::CacheStates::SD)
                ->ForkComp("### E.10.6.1. SD  -> MakeReadUnique -> SD  -> Comp")
                    ->Leaf("#### E.10.6.1.1. SD  -> MakeReadUnique -> SD  -> Comp_I           ", Resp::Comp_I     , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.6.1.2. SD  -> MakeReadUnique -> SD  -> Comp_UC    -> UD ", Resp::Comp_UC    , Xact::CacheStates::UD     , true )
                    ->Leaf("#### E.10.6.1.3. SD  -> MakeReadUnique -> SD  -> Comp_SC          ", Resp::Comp_SC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.6.1.4. SD  -> MakeReadUnique -> SD  -> Comp_UD_PD       ", Resp::Comp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkCompData("### E.10.6.2. SD  -> MakeReadUnique -> SD  -> CompData")
                    ->LeafRepeat("#### E.10.6.2.1. SD  -> MakeReadUnique -> SD  -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.6.2.2. SD  -> MakeReadUnique -> SD  -> CompData_UC    -> UD ", Resp::CompData_UC   , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.6.2.3. SD  -> MakeReadUnique -> SD  -> CompData_SC          ", Resp::CompData_SC   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.6.2.4. SD  -> MakeReadUnique -> SD  -> CompData_UD_PD       ", Resp::CompData_UD_PD, Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.6.2.5. SD  -> MakeReadUnique -> SD  -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.10.6.3. SD  -> MakeReadUnique -> SD  -> DataSepResp")
                    ->LeafRepeat("#### E.10.6.3.1. SD  -> MakeReadUnique -> SD  -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.6.3.2. SD  -> MakeReadUnique -> SD  -> DataSepResp_UC    -> UD ", Resp::DataSepResp_UC     , Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.6.3.3. SD  -> MakeReadUnique -> SD  -> DataSepResp_SC          ", Resp::DataSepResp_SC     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.6.3.4. SD  -> MakeReadUnique -> SD  -> DataSepResp_UD_PD       ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::None   , false)
                ->Rest()
            ->Rest()
            ->TestAndForkTransfer("## E.10.7. SD  -> MakeReadUnique -> I   ", Xact::CacheStates::SD, Xact::CacheStates::I)
                ->ForkComp("### E.10.7.1. SD  -> MakeReadUnique -> I   -> Comp")
                    ->Leaf("#### E.10.7.1.1. SD  -> MakeReadUnique -> I   -> Comp_I           ", Resp::Comp_I     , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.7.1.2. SD  -> MakeReadUnique -> I   -> Comp_UC          ", Resp::Comp_UC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.7.1.3. SD  -> MakeReadUnique -> I   -> Comp_SC          ", Resp::Comp_SC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.7.1.4. SD  -> MakeReadUnique -> I   -> Comp_UD_PD       ", Resp::Comp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkCompData("### E.10.7.2. SD  -> MakeReadUnique -> I   -> CompData")
                    ->LeafRepeat("#### E.10.7.2.1. SD  -> MakeReadUnique -> I   -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.7.2.2. SD  -> MakeReadUnique -> I   -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.7.2.3. SD  -> MakeReadUnique -> I   -> CompData_SC          ", Resp::CompData_SC   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.7.2.4. SD  -> MakeReadUnique -> I   -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD, Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.7.2.5. SD  -> MakeReadUnique -> I   -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.10.7.3. SD  -> MakeReadUnique -> I   -> DataSepResp")
                    ->LeafRepeat("#### E.10.7.3.1. SD  -> MakeReadUnique -> I   -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.7.3.2. SD  -> MakeReadUnique -> I   -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.7.3.3. SD  -> MakeReadUnique -> I   -> DataSepResp_SC          ", Resp::DataSepResp_SC     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.7.3.4. SD  -> MakeReadUnique -> I   -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

            ->TestAndLeafTransfer("## E.10.8. SC  -> MakeReadUnique -> UC  ", Xact::CacheStates::SC   , Xact::CacheStates::UC     , false)
            ->TestAndLeafTransfer("## E.10.9. SC  -> MakeReadUnique -> UCE ", Xact::CacheStates::SC   , Xact::CacheStates::UCE    , false)
            ->TestAndLeafTransfer("## E.10.10. SC  -> MakeReadUnique -> UD  ", Xact::CacheStates::SC   , Xact::CacheStates::UD     , false)
            ->TestAndLeafTransfer("## E.10.11. SC  -> MakeReadUnique -> UDP ", Xact::CacheStates::SC   , Xact::CacheStates::UDP    , false)
            ->TestAndForkTransfer("## E.10.12. SC  -> MakeReadUnique -> SC  ", Xact::CacheStates::SC, Xact::CacheStates::SC)
                ->ForkComp("### E.10.12.1. SC  -> MakeReadUnique -> SC  -> Comp")
                    ->Leaf("#### E.10.12.1.1. SC  -> MakeReadUnique -> SC  -> Comp_I           ", Resp::Comp_I     , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.12.1.2. SC  -> MakeReadUnique -> SC  -> Comp_UC    -> UC ", Resp::Comp_UC    , Xact::CacheStates::UC     , true )
                    ->Leaf("#### E.10.12.1.3. SC  -> MakeReadUnique -> SC  -> Comp_SC          ", Resp::Comp_SC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.12.1.4. SC  -> MakeReadUnique -> SC  -> Comp_UD_PD -> UD ", Resp::Comp_UD_PD , Xact::CacheStates::UD     , true )
                ->Rest()
                ->ForkCompData("### E.10.12.2. SC  -> MakeReadUnique -> SC  -> CompData")
                    ->LeafRepeat("#### E.10.12.2.1. SC  -> MakeReadUnique -> SC  -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.12.2.2. SC  -> MakeReadUnique -> SC  -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.12.2.3. SC  -> MakeReadUnique -> SC  -> CompData_SC          ", Resp::CompData_SC   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.12.2.4. SC  -> MakeReadUnique -> SC  -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD, Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.12.2.5. SC  -> MakeReadUnique -> SC  -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.10.12.3. SC  -> MakeReadUnique -> SC  -> DataSepResp")
                    ->LeafRepeat("#### E.10.12.3.1. SC  -> MakeReadUnique -> SC  -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.12.3.2. SC  -> MakeReadUnique -> SC  -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.12.3.3. SC  -> MakeReadUnique -> SC  -> DataSepResp_SC          ", Resp::DataSepResp_SC     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.12.3.4. SC  -> MakeReadUnique -> SC  -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()
            ->TestAndLeafTransfer("## E.10.13. SC  -> MakeReadUnique -> SD  ", Xact::CacheStates::SC  , Xact::CacheStates::SD     , false)
            ->TestAndForkTransfer("## E.10.14. SC  -> MakeReadUnique -> I   ", Xact::CacheStates::SC  , Xact::CacheStates::I)
                ->ForkComp("### E.10.14.1. SC  -> MakeReadUnique -> I   -> Comp")
                    ->Leaf("#### E.10.14.1.1. SC  -> MakeReadUnique -> I   -> Comp_I           ", Resp::Comp_I     , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.14.1.2. SC  -> MakeReadUnique -> I   -> Comp_UC          ", Resp::Comp_UC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.14.1.3. SC  -> MakeReadUnique -> I   -> Comp_SC          ", Resp::Comp_SC    , Xact::CacheStates::None   , false)
                    ->Leaf("#### E.10.14.1.4. SC  -> MakeReadUnique -> I   -> Comp_UD_PD       ", Resp::Comp_UD_PD , Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkCompData("### E.10.14.2. SC  -> MakeReadUnique -> I   -> CompData")
                    ->LeafRepeat("#### E.10.14.2.1. SC  -> MakeReadUnique -> I   -> CompData_I           ", Resp::CompData_I    , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.14.2.2. SC  -> MakeReadUnique -> I   -> CompData_UC    -> UC ", Resp::CompData_UC   , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.14.2.3. SC  -> MakeReadUnique -> I   -> CompData_SC          ", Resp::CompData_SC   , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.14.2.4. SC  -> MakeReadUnique -> I   -> CompData_UD_PD -> UD ", Resp::CompData_UD_PD, Xact::CacheStates::UD     , true )
                    ->LeafRepeat("#### E.10.14.2.5. SC  -> MakeReadUnique -> I   -> CompData_SD_PD       ", Resp::CompData_SD_PD, Xact::CacheStates::None   , false)
                ->Rest()
                ->ForkDataSepResp("### E.10.14.3. SC  -> MakeReadUnique -> I   -> DataSepResp")
                    ->LeafRepeat("#### E.10.14.3.1. SC  -> MakeReadUnique -> I   -> DataSepResp_I           ", Resp::DataSepResp_I      , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.14.3.2. SC  -> MakeReadUnique -> I   -> DataSepResp_UC    -> UC ", Resp::DataSepResp_UC     , Xact::CacheStates::UC     , true )
                    ->LeafRepeat("#### E.10.14.3.3. SC  -> MakeReadUnique -> I   -> DataSepResp_SC          ", Resp::DataSepResp_SC     , Xact::CacheStates::None   , false)
                    ->LeafRepeat("#### E.10.14.3.4. SC  -> MakeReadUnique -> I   -> DataSepResp_UD_PD -> UD ", Resp::DataSepResp_UD_PD  , Xact::CacheStates::UD     , true )
                ->Rest()
            ->Rest()

        ->End();

    tcptResp->End();
    tcptResp = nullptr;
}


#endif
