#include "tc_common_resp.hpp"           // IWYU pragma: keep
#include "tcpt_g_resp_write.hpp"        // IWYU pragma: keep

#ifdef CHI_ISSUE_E

void TCPtGRespWrite(
    size_t*                     totalCount,
    size_t*                     errCountFail,
    size_t*                     errCountEnvError,
    std::vector<std::string>*   errList,
    const Xact::Topology&       topo) noexcept
{
    TCPtResp* tcptResp = (new TCPtResp())
        ->TotalCount(totalCount)
        ->ErrCountFail(errCountFail)
        ->ErrCountEnvError(errCountEnvError)
        ->ErrList(errList)
        ->Topology(topo)
        ->Begin();

    tcptResp
        ->ForkREQ("# TCPt G.1. Response of WriteNoSnpPtl", Opcodes::REQ::WriteNoSnpPtl)
            ->TestAndForkInitial("## G.1.1. I   -> WriteNoSnpPtl", Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.1.1.1. I   -> WriteNoSnpPtl -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.1.1.1.1. I   -> WriteNoSnpPtl -> CompDBIDResp -> NonCopyBackWrData -> I  ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.1.1.2. I   -> WriteNoSnpPtl -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.1.1.2.1. I   -> WriteNoSnpPtl -> CompDBIDResp -> NCBWrDataCompAck -> I  ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.2. Response of WriteNoSnpFull", Opcodes::REQ::WriteNoSnpFull)
            ->TestAndForkInitial("## G.2.1. I   -> WriteNoSnpFull", Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.2.1.1. I   -> WriteNoSnpFull -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.2.1.1.1. I   -> WriteNoSnpFull -> CompDBIDResp -> NonCopyBackWrData -> I  ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.2.1.2. I   -> WriteNoSnpFull -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.2.1.2.1. I   -> WriteNoSnpFull -> CompDBIDResp -> NCBWrDataCompAck -> I  ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.3. Response of WriteNoSnpZero", Opcodes::REQ::WriteNoSnpZero)
            ->TestAndForkInitial("## G.3.1. I   -> WriteNoSnpZero", Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->Leaf("### G.3.1.1. I   -> WriteNoSnpZero -> CompDBIDResp -> I  ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.4. Response of WriteUniquePtl", Opcodes::REQ::WriteUniquePtl)
            ->TestAndForkTransfer("## G.4.1. I   -> WriteUniquePtl -> I   ", Xact::CacheStates::I, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.4.1.1. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.4.1.1.1. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> NonCopyBackWrData -> I   ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.4.1.2. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.4.1.2.1. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> NCBWrDataCompAck -> I   ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkWriteDataCancel("### G.4.1.3. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> WriteDataCancel")
                        ->LeafRepeat("#### G.4.1.3.1. I   -> WriteUniquePtl -> I   -> CompDBIDResp -> WriteDataCancel -> I   ", Resps::WriteDataCancel, Xact::CacheStates::I, true)
                    ->Rest()
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.5. Response of WriteUniquePtlStash", Opcodes::REQ::WriteUniquePtlStash)
            ->TestAndForkTransfer("## G.5.1. I   -> WriteUniquePtlStash -> I   ", Xact::CacheStates::I, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.5.1.1. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.5.1.1.1. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> NonCopyBackWrData -> I   ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.5.1.2. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.5.1.2.1. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> NCBWrDataCompAck -> I   ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkWriteDataCancel("### G.5.1.3. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> WriteDataCancel")
                        ->LeafRepeat("#### G.5.1.3.1. I   -> WriteUniquePtlStash -> I   -> CompDBIDResp -> WriteDataCancel -> I   ", Resps::WriteDataCancel, Xact::CacheStates::I, true)
                    ->Rest()
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.6. Response of WriteUniqueZero", Opcodes::REQ::WriteUniqueZero)
            ->TestAndForkTransfer("## G.6.1. I   -> WriteUniqueZero -> I   ", Xact::CacheStates::I, Xact::CacheStates::I)
                ->ForkComp("### G.6.1.1. I   -> WriteUniqueZero -> I   -> Comp ")
                    ->Leaf("#### G.6.1.1.1. I   -> WriteUniqueZero -> I   -> Comp -> I   ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
                ->ForkCompDBIDResp("### G.6.1.2. I   -> WriteUniqueZero -> I   -> CompDBIDResp")
                    ->Leaf("#### G.6.1.2.1. I   -> WriteUniqueZero -> I   -> CompDBIDResp -> I   ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.7. Response of WriteUniqueFull", Opcodes::REQ::WriteUniqueFull)
            ->TestAndForkTransfer("## G.7.1. I   -> WriteUniqueFull -> I   ", Xact::CacheStates::I, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.7.1.1. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.7.1.1.1. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> NonCopyBackWrData -> I   ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.7.1.2. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.7.1.2.1. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> NCBWrDataCompAck -> I   ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                    /*
                    ->ForkWriteDataCancel("### G.7.1.3. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> WriteDataCancel")
                        ->LeafRepeat("#### G.7.1.3.1. I   -> WriteUniqueFull -> I   -> CompDBIDResp -> WriteDataCancel -> I   ", Resps::WriteDataCancel, Xact::CacheStates::I, true)
                    ->Rest()
                    */
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.8. Response of WriteUniqueFullStash", Opcodes::REQ::WriteUniqueFullStash)
            ->TestAndForkTransfer("## G.8.1. I   -> WriteUniqueFullStash -> I   ", Xact::CacheStates::I, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkNonCopyBackWrData("### G.8.1.1. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> NonCopyBackWrData")
                        ->LeafRepeat("#### G.8.1.1.1. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> NonCopyBackWrData -> I   ", Resps::NonCopyBackWrData, Xact::CacheStates::I, true)
                    ->Rest()
                    ->ForkNCBWrDataCompAck("### G.8.1.2. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> NCBWrDataCompAck")
                        ->LeafRepeat("#### G.8.1.2.1. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> NCBWrDataCompAck -> I   ", Resps::NCBWrDataCompAck, Xact::CacheStates::I, true)
                    ->Rest()
                    /*
                    ->ForkWriteDataCancel("### G.8.1.3. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> WriteDataCancel")
                        ->LeafRepeat("#### G.8.1.3.1. I   -> WriteUniqueFullStash -> I   -> CompDBIDResp -> WriteDataCancel -> I   ", Resps::WriteDataCancel, Xact::CacheStates::I, true)
                    ->Rest()
                    */
                ->Rest()
            ->Rest()
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.9. Response of WriteBackFull", Opcodes::REQ::WriteBackFull)

            ->TestAndForkTransfer("## G.9.1. UD  -> WriteBackFull -> UD  ", Xact::CacheStates::UD, Xact::CacheStates::UD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.1.1. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.1.1.1. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.1.1.2. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.1.1.3. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.1.1.4. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData_UD_PD -> I   ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.9.1.1.5. UD  -> WriteBackFull -> UD  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.2. UD  -> WriteBackFull -> UC  ", Xact::CacheStates::UD, Xact::CacheStates::UC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.2.1. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.2.1.1. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.2.1.2. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData_UC    -> I   ", Resps::CopyBackWrData_UC   , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.9.2.1.3. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.2.1.4. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.2.1.5. UD  -> WriteBackFull -> UC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.3. UD  -> WriteBackFull -> SD  ", Xact::CacheStates::UD, Xact::CacheStates::SD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.3.1. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.3.1.1. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.3.1.2. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.3.1.3. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.3.1.4. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.3.1.5. UD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_SD_PD -> I   ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::I      , true )
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.4. UD  -> WriteBackFull -> SC  ", Xact::CacheStates::UD, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.4.1. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.4.1.1. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.4.1.2. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.4.1.3. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> I   ", Resps::CopyBackWrData_SC   , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.9.4.1.4. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.4.1.5. UD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.5. UD  -> WriteBackFull -> I   ", Xact::CacheStates::UD, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.5.1. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.5.1.1. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I    , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.9.5.1.2. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.5.1.3. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.5.1.4. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.5.1.5. UD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.6. SD  -> WriteBackFull -> SD  ", Xact::CacheStates::SD, Xact::CacheStates::SD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.6.1. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.6.1.1. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.6.1.2. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.6.1.3. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.6.1.4. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.6.1.5. SD  -> WriteBackFull -> SD  -> CompDBIDResp -> CopyBackWrData_SD_PD -> I   ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::I      , true )
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.7. SD  -> WriteBackFull -> SC  ", Xact::CacheStates::SD, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.7.1. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.7.1.1. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.7.1.2. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.7.1.3. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> I   ", Resps::CopyBackWrData_SC   , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.9.7.1.4. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.7.1.5. SD  -> WriteBackFull -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.9.8. SD  -> WriteBackFull -> I   ", Xact::CacheStates::SD, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.9.8.1. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.9.8.1.1. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I    , Xact::CacheStates::I      , true)
                        ->LeafRepeat("#### G.9.8.1.2. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.8.1.3. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.8.1.4. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.9.8.1.5. SD  -> WriteBackFull -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()
            
        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.10. Response of WriteBackPtl", Opcodes::REQ::WriteBackPtl)

            ->TestAndForkTransfer("## G.10.1. UDP -> WriteBackPtl -> UDP ", Xact::CacheStates::UDP, Xact::CacheStates::UDP)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.10.1.1. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.10.1.1.1. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.1.1.2. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.1.1.3. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.1.1.4. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData_UD_PD -> I   ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.10.1.1.5. UDP -> WriteBackPtl -> UDP -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.10.2. UDP -> WriteBackPtl -> I   ", Xact::CacheStates::UDP, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.10.2.1. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.10.2.1.1. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I    , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.10.2.1.2. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.2.1.3. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC   , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.2.1.4. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD -> I   ", Resps::CopyBackWrData_UD_PD, Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.10.2.1.5. UDP -> WriteBackPtl -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD, Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.11. Response of WriteCleanFull", Opcodes::REQ::WriteCleanFull)

            ->TestAndForkTransfer("## G.11.1. UD  -> WriteCleanFull -> UD  ", Xact::CacheStates::UD, Xact::CacheStates::UD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.1.1. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.1.1.1. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.1.1.2. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.1.1.3. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.1.1.4. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData_UD_PD -> UC  ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::UC     , true )
                        ->LeafRepeat("#### G.11.1.1.5. UD  -> WriteCleanFull -> UD  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()
            
            ->TestAndForkTransfer("## G.11.2. UD  -> WriteCleanFull -> UC  ", Xact::CacheStates::UD, Xact::CacheStates::UC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.2.1. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.2.1.1. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.2.1.2. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData_UC    -> UC  ", Resps::CopyBackWrData_UC     , Xact::CacheStates::UC     , true )
                        ->LeafRepeat("#### G.11.2.1.3. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.2.1.4. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.2.1.5. UD  -> WriteCleanFull -> UC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.3. UD  -> WriteCleanFull -> SD  ", Xact::CacheStates::UD, Xact::CacheStates::SD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.3.1. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.3.1.1. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.3.1.2. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.3.1.3. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.3.1.4. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.3.1.5. UD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_SD_PD -> SC  ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::SC     , true )
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.4. UD  -> WriteCleanFull -> SC  ", Xact::CacheStates::UD, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.4.1. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.4.1.1. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.4.1.2. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.4.1.3. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> SC  ", Resps::CopyBackWrData_SC     , Xact::CacheStates::SC     , true )
                        ->LeafRepeat("#### G.11.4.1.4. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.4.1.5. UD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.5. UD  -> WriteCleanFull -> I   ", Xact::CacheStates::UD, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.5.1. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.5.1.1. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I      , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.11.5.1.2. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.5.1.3. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.5.1.4. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.5.1.5. UD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.6. SD  -> WriteCleanFull -> SD  ", Xact::CacheStates::SD, Xact::CacheStates::SD)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.6.1. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.6.1.1. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.6.1.2. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.6.1.3. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.6.1.4. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.6.1.5. SD  -> WriteCleanFull -> SD  -> CompDBIDResp -> CopyBackWrData_SD_PD -> SC  ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::SC     , true )
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.7. SD  -> WriteCleanFull -> SC  ", Xact::CacheStates::SD, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.7.1. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.7.1.1. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.7.1.2. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.7.1.3. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> SC  ", Resps::CopyBackWrData_SC     , Xact::CacheStates::SC     , true )
                        ->LeafRepeat("#### G.11.7.1.4. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.7.1.5. SD  -> WriteCleanFull -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.11.8. SD  -> WriteCleanFull -> I   ", Xact::CacheStates::SD, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.11.8.1. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.11.8.1.1. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I      , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.11.8.1.2. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.8.1.3. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.8.1.4. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.11.8.1.5. SD  -> WriteCleanFull -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.12. Response of WriteEvictFull", Opcodes::REQ::WriteEvictFull)

            ->TestAndForkTransfer("## G.12.1. UC  -> WriteEvictFull -> UC  ", Xact::CacheStates::UC, Xact::CacheStates::UC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.12.1.1. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.12.1.1.1. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.1.1.2. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData_UC    -> I   ", Resps::CopyBackWrData_UC     , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.12.1.1.3. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.1.1.4. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.1.1.5. UC  -> WriteEvictFull -> UC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.12.2. UC  -> WriteEvictFull -> SC  ", Xact::CacheStates::UC, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.12.2.1. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.12.2.1.1. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData_I            ", Resps::CopyBackWrData_I      , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.2.1.2. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.2.1.3. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> I   ", Resps::CopyBackWrData_SC     , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.12.2.1.4. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.2.1.5. UC  -> WriteEvictFull -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.12.3. UC  -> WriteEvictFull -> I   ", Xact::CacheStates::UC, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.12.3.1. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.12.3.1.1. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I   ", Resps::CopyBackWrData_I      , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.12.3.1.2. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData_UC           ", Resps::CopyBackWrData_UC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.3.1.3. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData_SC           ", Resps::CopyBackWrData_SC     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.3.1.4. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD        ", Resps::CopyBackWrData_UD_PD  , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.12.3.1.5. UC  -> WriteEvictFull -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD        ", Resps::CopyBackWrData_SD_PD  , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
            ->Rest()

        ->End();

    tcptResp
        ->ForkREQ("# TCPt G.13. Response of WriteEvictOrEvict", Opcodes::REQ::WriteEvictOrEvict)

            ->TestAndForkTransfer("## G.13.1. UC  -> WriteEvictOrEvict -> UC  ", Xact::CacheStates::UC, Xact::CacheStates::UC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.13.1.1. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.13.1.1.1. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData_I          ", Resps::CopyBackWrData_I     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.1.1.2. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData_UC    -> I ", Resps::CopyBackWrData_UC    , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.13.1.1.3. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData_SC         ", Resps::CopyBackWrData_SC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.1.1.4. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData_UD_PD      ", Resps::CopyBackWrData_UD_PD , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.1.1.5. UC  -> WriteEvictOrEvict -> UC  -> CompDBIDResp -> CopyBackWrData_SD_PD      ", Resps::CopyBackWrData_SD_PD , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
                ->ForkComp("### G.13.1.2. UC  -> WriteEvictOrEvict -> UC  -> Comp")
                    ->Leaf("#### G.13.1.2.1. UC  -> WriteEvictOrEvict -> UC  -> Comp -> I ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.13.2. UC  -> WriteEvictOrEvict -> SC  ", Xact::CacheStates::UC, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.13.2.1. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.13.2.1.1. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_I          ", Resps::CopyBackWrData_I     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.2.1.2. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_UC         ", Resps::CopyBackWrData_UC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.2.1.3. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> I ", Resps::CopyBackWrData_SC    , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.13.2.1.4. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD      ", Resps::CopyBackWrData_UD_PD , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.2.1.5. UC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD      ", Resps::CopyBackWrData_SD_PD , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
                ->ForkComp("### G.13.2.2. UC  -> WriteEvictOrEvict -> SC  -> Comp")
                    ->Leaf("#### G.13.2.2.1. UC  -> WriteEvictOrEvict -> SC  -> Comp -> I ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.13.3. UC  -> WriteEvictOrEvict -> I   ", Xact::CacheStates::UC, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.13.3.1. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.13.3.1.1. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I ", Resps::CopyBackWrData_I     , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.13.3.1.2. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_UC         ", Resps::CopyBackWrData_UC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.3.1.3. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_SC         ", Resps::CopyBackWrData_SC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.3.1.4. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD      ", Resps::CopyBackWrData_UD_PD , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.3.1.5. UC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD      ", Resps::CopyBackWrData_SD_PD , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
                ->ForkComp("### G.13.3.2. UC  -> WriteEvictOrEvict -> I   -> Comp")
                    ->Leaf("#### G.13.3.2.1. UC  -> WriteEvictOrEvict -> I   -> Comp -> I ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.13.4. SC  -> WriteEvictOrEvict -> SC  ", Xact::CacheStates::SC, Xact::CacheStates::SC)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.13.4.1. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.13.4.1.1. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_I          ", Resps::CopyBackWrData_I     , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.4.1.2. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_UC         ", Resps::CopyBackWrData_UC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.4.1.3. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_SC    -> I ", Resps::CopyBackWrData_SC    , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.13.4.1.4. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_UD_PD      ", Resps::CopyBackWrData_UD_PD , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.4.1.5. SC  -> WriteEvictOrEvict -> SC  -> CompDBIDResp -> CopyBackWrData_SD_PD      ", Resps::CopyBackWrData_SD_PD , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
                ->ForkComp("### G.13.4.2. SC  -> WriteEvictOrEvict -> SC  -> Comp")
                    ->Leaf("#### G.13.4.2.1. SC  -> WriteEvictOrEvict -> SC  -> Comp -> I ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()

            ->TestAndForkTransfer("## G.13.5. SC  -> WriteEvictOrEvict -> I   ", Xact::CacheStates::SC, Xact::CacheStates::I)
                ->ForkInstantCompDBIDResp("")
                    ->ForkCopyBackWrData("### G.13.5.1. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData")
                        ->LeafRepeat("#### G.13.5.1.1. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_I     -> I ", Resps::CopyBackWrData_I     , Xact::CacheStates::I      , true )
                        ->LeafRepeat("#### G.13.5.1.2. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_UC         ", Resps::CopyBackWrData_UC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.5.1.3. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_SC         ", Resps::CopyBackWrData_SC    , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.5.1.4. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_UD_PD      ", Resps::CopyBackWrData_UD_PD , Xact::CacheStates::None   , false)
                        ->LeafRepeat("#### G.13.5.1.5. SC  -> WriteEvictOrEvict -> I   -> CompDBIDResp -> CopyBackWrData_SD_PD      ", Resps::CopyBackWrData_SD_PD , Xact::CacheStates::None   , false)
                    ->Rest()
                ->Rest()
                ->ForkComp("### G.13.5.2. SC  -> WriteEvictOrEvict -> I   -> Comp")
                    ->Leaf("#### G.13.5.2.1. SC  -> WriteEvictOrEvict -> I   -> Comp -> I ", Resps::Comp_I, Xact::CacheStates::I, true)
                ->Rest()
            ->Rest()

        ->End();

    tcptResp->End();
    tcptResp = nullptr;
}

#endif
