#include "tc_common_initial.hpp"            // IWYU pragma: keep
#include "tcpt_d_initial_atomic.hpp"        // IWYU pragma: keep

#ifdef CHI_ISSUE_E

void TCPtDInitialAtomic(
    size_t*                     totalCount,
    size_t*                     errCountFail,
    size_t*                     errCountEnvError,
    std::vector<std::string>*   errList,
    const Xact::Topology&       topo) noexcept
{
    TCPtInitial* tcptInitial = (new TCPtInitial())
        ->TotalCount(totalCount)
        ->ErrCountFail(errCountFail)
        ->ErrCountEnvError(errCountEnvError)
        ->ErrList(errList)
        ->Topology(topo)
        ->Begin();

    tcptInitial
        ->ForkREQ("# TCPt D.1. Initial state of AtomicStore::ADD", Opcodes::REQ::AtomicStore::ADD)

            ->ForkSilentTransitions("## D.1.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.1.1.1. UC  -> AtomicStore::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.1.1.2. UCE -> AtomicStore::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.1.1.3. UD  -> AtomicStore::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.1.1.4. UDP -> AtomicStore::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.1.1.5. SC  -> AtomicStore::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.1.1.6. SD  -> AtomicStore::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.1.1.7. I   -> AtomicStore::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.1.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.1.2.1. UC  -> AtomicStore::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.1.2.2. UCE -> AtomicStore::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.1.2.3. UD  -> AtomicStore::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.1.2.4. UDP -> AtomicStore::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.1.2.5. SC  -> AtomicStore::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.1.2.6. SD  -> AtomicStore::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.1.2.7. I   -> AtomicStore::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.1.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.1.3.1. UC  -> AtomicStore::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.1.3.2. UCE -> AtomicStore::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.1.3.3. UD  -> AtomicStore::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.1.3.4. UDP -> AtomicStore::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.1.3.5. SC  -> AtomicStore::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.1.3.6. SD  -> AtomicStore::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.1.3.7. I   -> AtomicStore::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.1.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.1.4.1. UC  -> AtomicStore::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.1.4.2. UCE -> AtomicStore::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.1.4.3. UD  -> AtomicStore::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.1.4.4. UDP -> AtomicStore::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.1.4.5. SC  -> AtomicStore::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.1.4.6. SD  -> AtomicStore::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.1.4.7. I   -> AtomicStore::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.1.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.1.5.1. UC  -> AtomicStore::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.1.5.2. UCE -> AtomicStore::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.1.5.3. UD  -> AtomicStore::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.1.5.4. UDP -> AtomicStore::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.1.5.5. SC  -> AtomicStore::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.1.5.6. SD  -> AtomicStore::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.1.5.7. I   -> AtomicStore::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.2. Initial state of AtomicStore::CLR", Opcodes::REQ::AtomicStore::CLR)

            ->ForkSilentTransitions("## D.2.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.2.1.1. UC  -> AtomicStore::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.2.1.2. UCE -> AtomicStore::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.2.1.3. UD  -> AtomicStore::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.2.1.4. UDP -> AtomicStore::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.2.1.5. SC  -> AtomicStore::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.2.1.6. SD  -> AtomicStore::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.2.1.7. I   -> AtomicStore::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.2.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.2.2.1. UC  -> AtomicStore::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.2.2.2. UCE -> AtomicStore::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.2.2.3. UD  -> AtomicStore::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.2.2.4. UDP -> AtomicStore::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.2.2.5. SC  -> AtomicStore::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.2.2.6. SD  -> AtomicStore::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.2.2.7. I   -> AtomicStore::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.2.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.2.3.1. UC  -> AtomicStore::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.2.3.2. UCE -> AtomicStore::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.2.3.3. UD  -> AtomicStore::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.2.3.4. UDP -> AtomicStore::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.2.3.5. SC  -> AtomicStore::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.2.3.6. SD  -> AtomicStore::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.2.3.7. I   -> AtomicStore::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.2.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.2.4.1. UC  -> AtomicStore::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.2.4.2. UCE -> AtomicStore::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.2.4.3. UD  -> AtomicStore::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.2.4.4. UDP -> AtomicStore::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.2.4.5. SC  -> AtomicStore::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.2.4.6. SD  -> AtomicStore::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.2.4.7. I   -> AtomicStore::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.2.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.2.5.1. UC  -> AtomicStore::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.2.5.2. UCE -> AtomicStore::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.2.5.3. UD  -> AtomicStore::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.2.5.4. UDP -> AtomicStore::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.2.5.5. SC  -> AtomicStore::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.2.5.6. SD  -> AtomicStore::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.2.5.7. I   -> AtomicStore::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.3. Initial state of AtomicStore::EOR", Opcodes::REQ::AtomicStore::EOR)

            ->ForkSilentTransitions("## D.3.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.3.1.1. UC  -> AtomicStore::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.3.1.2. UCE -> AtomicStore::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.3.1.3. UD  -> AtomicStore::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.3.1.4. UDP -> AtomicStore::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.3.1.5. SC  -> AtomicStore::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.3.1.6. SD  -> AtomicStore::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.3.1.7. I   -> AtomicStore::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.3.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.3.2.1. UC  -> AtomicStore::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.3.2.2. UCE -> AtomicStore::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.3.2.3. UD  -> AtomicStore::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.3.2.4. UDP -> AtomicStore::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.3.2.5. SC  -> AtomicStore::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.3.2.6. SD  -> AtomicStore::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.3.2.7. I   -> AtomicStore::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.3.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.3.3.1. UC  -> AtomicStore::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.3.3.2. UCE -> AtomicStore::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.3.3.3. UD  -> AtomicStore::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.3.3.4. UDP -> AtomicStore::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.3.3.5. SC  -> AtomicStore::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.3.3.6. SD  -> AtomicStore::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.3.3.7. I   -> AtomicStore::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.3.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.3.4.1. UC  -> AtomicStore::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.3.4.2. UCE -> AtomicStore::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.3.4.3. UD  -> AtomicStore::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.3.4.4. UDP -> AtomicStore::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.3.4.5. SC  -> AtomicStore::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.3.4.6. SD  -> AtomicStore::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.3.4.7. I   -> AtomicStore::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.3.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.3.5.1. UC  -> AtomicStore::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.3.5.2. UCE -> AtomicStore::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.3.5.3. UD  -> AtomicStore::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.3.5.4. UDP -> AtomicStore::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.3.5.5. SC  -> AtomicStore::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.3.5.6. SD  -> AtomicStore::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.3.5.7. I   -> AtomicStore::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.4. Initial state of AtomicStore::SET", Opcodes::REQ::AtomicStore::SET)

            ->ForkSilentTransitions("## D.4.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.4.1.1. UC  -> AtomicStore::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.4.1.2. UCE -> AtomicStore::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.4.1.3. UD  -> AtomicStore::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.4.1.4. UDP -> AtomicStore::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.4.1.5. SC  -> AtomicStore::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.4.1.6. SD  -> AtomicStore::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.4.1.7. I   -> AtomicStore::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.4.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.4.2.1. UC  -> AtomicStore::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.4.2.2. UCE -> AtomicStore::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.4.2.3. UD  -> AtomicStore::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.4.2.4. UDP -> AtomicStore::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.4.2.5. SC  -> AtomicStore::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.4.2.6. SD  -> AtomicStore::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.4.2.7. I   -> AtomicStore::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.4.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.4.3.1. UC  -> AtomicStore::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.4.3.2. UCE -> AtomicStore::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.4.3.3. UD  -> AtomicStore::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.4.3.4. UDP -> AtomicStore::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.4.3.5. SC  -> AtomicStore::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.4.3.6. SD  -> AtomicStore::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.4.3.7. I   -> AtomicStore::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.4.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.4.4.1. UC  -> AtomicStore::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.4.4.2. UCE -> AtomicStore::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.4.4.3. UD  -> AtomicStore::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.4.4.4. UDP -> AtomicStore::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.4.4.5. SC  -> AtomicStore::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.4.4.6. SD  -> AtomicStore::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.4.4.7. I   -> AtomicStore::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.4.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.4.5.1. UC  -> AtomicStore::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.4.5.2. UCE -> AtomicStore::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.4.5.3. UD  -> AtomicStore::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.4.5.4. UDP -> AtomicStore::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.4.5.5. SC  -> AtomicStore::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.4.5.6. SD  -> AtomicStore::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.4.5.7. I   -> AtomicStore::SET ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.5. Initial state of AtomicStore::SMAX", Opcodes::REQ::AtomicStore::SMAX)

            ->ForkSilentTransitions("## D.5.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.5.1.1. UC  -> AtomicStore::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.5.1.2. UCE -> AtomicStore::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.5.1.3. UD  -> AtomicStore::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.5.1.4. UDP -> AtomicStore::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.5.1.5. SC  -> AtomicStore::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.5.1.6. SD  -> AtomicStore::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.5.1.7. I   -> AtomicStore::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.5.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.5.2.1. UC  -> AtomicStore::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.5.2.2. UCE -> AtomicStore::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.5.2.3. UD  -> AtomicStore::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.5.2.4. UDP -> AtomicStore::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.5.2.5. SC  -> AtomicStore::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.5.2.6. SD  -> AtomicStore::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.5.2.7. I   -> AtomicStore::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.5.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.5.3.1. UC  -> AtomicStore::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.5.3.2. UCE -> AtomicStore::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.5.3.3. UD  -> AtomicStore::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.5.3.4. UDP -> AtomicStore::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.5.3.5. SC  -> AtomicStore::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.5.3.6. SD  -> AtomicStore::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.5.3.7. I   -> AtomicStore::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.5.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.5.4.1. UC  -> AtomicStore::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.5.4.2. UCE -> AtomicStore::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.5.4.3. UD  -> AtomicStore::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.5.4.4. UDP -> AtomicStore::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.5.4.5. SC  -> AtomicStore::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.5.4.6. SD  -> AtomicStore::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.5.4.7. I   -> AtomicStore::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.5.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.5.5.1. UC  -> AtomicStore::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.5.5.2. UCE -> AtomicStore::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.5.5.3. UD  -> AtomicStore::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.5.5.4. UDP -> AtomicStore::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.5.5.5. SC  -> AtomicStore::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.5.5.6. SD  -> AtomicStore::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.5.5.7. I   -> AtomicStore::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.6. Initial state of AtomicStore::SMIN", Opcodes::REQ::AtomicStore::SMIN)

            ->ForkSilentTransitions("## D.6.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.6.1.1. UC  -> AtomicStore::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.6.1.2. UCE -> AtomicStore::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.6.1.3. UD  -> AtomicStore::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.6.1.4. UDP -> AtomicStore::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.6.1.5. SC  -> AtomicStore::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.6.1.6. SD  -> AtomicStore::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.6.1.7. I   -> AtomicStore::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.6.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.6.2.1. UC  -> AtomicStore::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.6.2.2. UCE -> AtomicStore::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.6.2.3. UD  -> AtomicStore::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.6.2.4. UDP -> AtomicStore::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.6.2.5. SC  -> AtomicStore::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.6.2.6. SD  -> AtomicStore::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.6.2.7. I   -> AtomicStore::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.6.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.6.3.1. UC  -> AtomicStore::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.6.3.2. UCE -> AtomicStore::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.6.3.3. UD  -> AtomicStore::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.6.3.4. UDP -> AtomicStore::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.6.3.5. SC  -> AtomicStore::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.6.3.6. SD  -> AtomicStore::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.6.3.7. I   -> AtomicStore::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.6.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.6.4.1. UC  -> AtomicStore::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.6.4.2. UCE -> AtomicStore::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.6.4.3. UD  -> AtomicStore::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.6.4.4. UDP -> AtomicStore::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.6.4.5. SC  -> AtomicStore::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.6.4.6. SD  -> AtomicStore::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.6.4.7. I   -> AtomicStore::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.6.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.6.5.1. UC  -> AtomicStore::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.6.5.2. UCE -> AtomicStore::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.6.5.3. UD  -> AtomicStore::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.6.5.4. UDP -> AtomicStore::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.6.5.5. SC  -> AtomicStore::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.6.5.6. SD  -> AtomicStore::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.6.5.7. I   -> AtomicStore::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.7. Initial state of AtomicStore::UMAX", Opcodes::REQ::AtomicStore::UMAX)

            ->ForkSilentTransitions("## D.7.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.7.1.1. UC  -> AtomicStore::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.7.1.2. UCE -> AtomicStore::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.7.1.3. UD  -> AtomicStore::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.7.1.4. UDP -> AtomicStore::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.7.1.5. SC  -> AtomicStore::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.7.1.6. SD  -> AtomicStore::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.7.1.7. I   -> AtomicStore::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.7.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.7.2.1. UC  -> AtomicStore::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.7.2.2. UCE -> AtomicStore::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.7.2.3. UD  -> AtomicStore::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.7.2.4. UDP -> AtomicStore::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.7.2.5. SC  -> AtomicStore::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.7.2.6. SD  -> AtomicStore::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.7.2.7. I   -> AtomicStore::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.7.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.7.3.1. UC  -> AtomicStore::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.7.3.2. UCE -> AtomicStore::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.7.3.3. UD  -> AtomicStore::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.7.3.4. UDP -> AtomicStore::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.7.3.5. SC  -> AtomicStore::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.7.3.6. SD  -> AtomicStore::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.7.3.7. I   -> AtomicStore::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.7.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.7.4.1. UC  -> AtomicStore::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.7.4.2. UCE -> AtomicStore::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.7.4.3. UD  -> AtomicStore::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.7.4.4. UDP -> AtomicStore::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.7.4.5. SC  -> AtomicStore::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.7.4.6. SD  -> AtomicStore::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.7.4.7. I   -> AtomicStore::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.7.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.7.5.1. UC  -> AtomicStore::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.7.5.2. UCE -> AtomicStore::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.7.5.3. UD  -> AtomicStore::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.7.5.4. UDP -> AtomicStore::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.7.5.5. SC  -> AtomicStore::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.7.5.6. SD  -> AtomicStore::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.7.5.7. I   -> AtomicStore::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.8. Initial state of AtomicStore::UMIN", Opcodes::REQ::AtomicStore::UMIN)

            ->ForkSilentTransitions("## D.8.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.8.1.1. UC  -> AtomicStore::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.8.1.2. UCE -> AtomicStore::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.8.1.3. UD  -> AtomicStore::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.8.1.4. UDP -> AtomicStore::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.8.1.5. SC  -> AtomicStore::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.8.1.6. SD  -> AtomicStore::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.8.1.7. I   -> AtomicStore::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.8.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.8.2.1. UC  -> AtomicStore::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.8.2.2. UCE -> AtomicStore::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.8.2.3. UD  -> AtomicStore::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.8.2.4. UDP -> AtomicStore::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.8.2.5. SC  -> AtomicStore::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.8.2.6. SD  -> AtomicStore::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.8.2.7. I   -> AtomicStore::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.8.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.8.3.1. UC  -> AtomicStore::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.8.3.2. UCE -> AtomicStore::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.8.3.3. UD  -> AtomicStore::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.8.3.4. UDP -> AtomicStore::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.8.3.5. SC  -> AtomicStore::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.8.3.6. SD  -> AtomicStore::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.8.3.7. I   -> AtomicStore::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.8.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.8.4.1. UC  -> AtomicStore::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.8.4.2. UCE -> AtomicStore::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.8.4.3. UD  -> AtomicStore::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.8.4.4. UDP -> AtomicStore::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.8.4.5. SC  -> AtomicStore::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.8.4.6. SD  -> AtomicStore::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.8.4.7. I   -> AtomicStore::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.8.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.8.5.1. UC  -> AtomicStore::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.8.5.2. UCE -> AtomicStore::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.8.5.3. UD  -> AtomicStore::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.8.5.4. UDP -> AtomicStore::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.8.5.5. SC  -> AtomicStore::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.8.5.6. SD  -> AtomicStore::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.8.5.7. I   -> AtomicStore::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.9. Initial state of AtomicLoad::ADD", Opcodes::REQ::AtomicLoad::ADD)

            ->ForkSilentTransitions("## D.9.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.9.1.1. UC  -> AtomicLoad::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.9.1.2. UCE -> AtomicLoad::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.9.1.3. UD  -> AtomicLoad::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.9.1.4. UDP -> AtomicLoad::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.9.1.5. SC  -> AtomicLoad::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.9.1.6. SD  -> AtomicLoad::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.9.1.7. I   -> AtomicLoad::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.9.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.9.2.1. UC  -> AtomicLoad::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.9.2.2. UCE -> AtomicLoad::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.9.2.3. UD  -> AtomicLoad::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.9.2.4. UDP -> AtomicLoad::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.9.2.5. SC  -> AtomicLoad::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.9.2.6. SD  -> AtomicLoad::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.9.2.7. I   -> AtomicLoad::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.9.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.9.3.1. UC  -> AtomicLoad::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.9.3.2. UCE -> AtomicLoad::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.9.3.3. UD  -> AtomicLoad::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.9.3.4. UDP -> AtomicLoad::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.9.3.5. SC  -> AtomicLoad::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.9.3.6. SD  -> AtomicLoad::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.9.3.7. I   -> AtomicLoad::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.9.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.9.4.1. UC  -> AtomicLoad::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.9.4.2. UCE -> AtomicLoad::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.9.4.3. UD  -> AtomicLoad::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.9.4.4. UDP -> AtomicLoad::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.9.4.5. SC  -> AtomicLoad::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.9.4.6. SD  -> AtomicLoad::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.9.4.7. I   -> AtomicLoad::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.9.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.9.5.1. UC  -> AtomicLoad::ADD ", Xact::CacheStates::UC , true )
                ->Leaf("### D.9.5.2. UCE -> AtomicLoad::ADD ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.9.5.3. UD  -> AtomicLoad::ADD ", Xact::CacheStates::UD , true )
                ->Leaf("### D.9.5.4. UDP -> AtomicLoad::ADD ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.9.5.5. SC  -> AtomicLoad::ADD ", Xact::CacheStates::SC , true )
                ->Leaf("### D.9.5.6. SD  -> AtomicLoad::ADD ", Xact::CacheStates::SD , true )
                ->Leaf("### D.9.5.7. I   -> AtomicLoad::ADD ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.10. Initial state of AtomicLoad::CLR", Opcodes::REQ::AtomicLoad::CLR)

            ->ForkSilentTransitions("## D.10.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.10.1.1. UC  -> AtomicLoad::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.10.1.2. UCE -> AtomicLoad::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.10.1.3. UD  -> AtomicLoad::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.10.1.4. UDP -> AtomicLoad::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.10.1.5. SC  -> AtomicLoad::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.10.1.6. SD  -> AtomicLoad::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.10.1.7. I   -> AtomicLoad::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.10.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.10.2.1. UC  -> AtomicLoad::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.10.2.2. UCE -> AtomicLoad::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.10.2.3. UD  -> AtomicLoad::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.10.2.4. UDP -> AtomicLoad::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.10.2.5. SC  -> AtomicLoad::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.10.2.6. SD  -> AtomicLoad::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.10.2.7. I   -> AtomicLoad::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.10.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.10.3.1. UC  -> AtomicLoad::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.10.3.2. UCE -> AtomicLoad::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.10.3.3. UD  -> AtomicLoad::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.10.3.4. UDP -> AtomicLoad::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.10.3.5. SC  -> AtomicLoad::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.10.3.6. SD  -> AtomicLoad::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.10.3.7. I   -> AtomicLoad::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.10.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.10.4.1. UC  -> AtomicLoad::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.10.4.2. UCE -> AtomicLoad::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.10.4.3. UD  -> AtomicLoad::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.10.4.4. UDP -> AtomicLoad::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.10.4.5. SC  -> AtomicLoad::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.10.4.6. SD  -> AtomicLoad::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.10.4.7. I   -> AtomicLoad::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.10.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.10.5.1. UC  -> AtomicLoad::CLR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.10.5.2. UCE -> AtomicLoad::CLR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.10.5.3. UD  -> AtomicLoad::CLR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.10.5.4. UDP -> AtomicLoad::CLR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.10.5.5. SC  -> AtomicLoad::CLR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.10.5.6. SD  -> AtomicLoad::CLR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.10.5.7. I   -> AtomicLoad::CLR ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.11. Initial state of AtomicLoad::EOR", Opcodes::REQ::AtomicLoad::EOR)

            ->ForkSilentTransitions("## D.11.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.11.1.1. UC  -> AtomicLoad::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.11.1.2. UCE -> AtomicLoad::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.11.1.3. UD  -> AtomicLoad::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.11.1.4. UDP -> AtomicLoad::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.11.1.5. SC  -> AtomicLoad::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.11.1.6. SD  -> AtomicLoad::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.11.1.7. I   -> AtomicLoad::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.11.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.11.2.1. UC  -> AtomicLoad::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.11.2.2. UCE -> AtomicLoad::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.11.2.3. UD  -> AtomicLoad::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.11.2.4. UDP -> AtomicLoad::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.11.2.5. SC  -> AtomicLoad::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.11.2.6. SD  -> AtomicLoad::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.11.2.7. I   -> AtomicLoad::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.11.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.11.3.1. UC  -> AtomicLoad::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.11.3.2. UCE -> AtomicLoad::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.11.3.3. UD  -> AtomicLoad::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.11.3.4. UDP -> AtomicLoad::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.11.3.5. SC  -> AtomicLoad::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.11.3.6. SD  -> AtomicLoad::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.11.3.7. I   -> AtomicLoad::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.11.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.11.4.1. UC  -> AtomicLoad::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.11.4.2. UCE -> AtomicLoad::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.11.4.3. UD  -> AtomicLoad::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.11.4.4. UDP -> AtomicLoad::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.11.4.5. SC  -> AtomicLoad::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.11.4.6. SD  -> AtomicLoad::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.11.4.7. I   -> AtomicLoad::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.11.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.11.5.1. UC  -> AtomicLoad::EOR ", Xact::CacheStates::UC , true )
                ->Leaf("### D.11.5.2. UCE -> AtomicLoad::EOR ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.11.5.3. UD  -> AtomicLoad::EOR ", Xact::CacheStates::UD , true )
                ->Leaf("### D.11.5.4. UDP -> AtomicLoad::EOR ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.11.5.5. SC  -> AtomicLoad::EOR ", Xact::CacheStates::SC , true )
                ->Leaf("### D.11.5.6. SD  -> AtomicLoad::EOR ", Xact::CacheStates::SD , true )
                ->Leaf("### D.11.5.7. I   -> AtomicLoad::EOR ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.12. Initial state of AtomicLoad::SET", Opcodes::REQ::AtomicLoad::SET)

            ->ForkSilentTransitions("## D.12.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.12.1.1. UC  -> AtomicLoad::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.12.1.2. UCE -> AtomicLoad::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.12.1.3. UD  -> AtomicLoad::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.12.1.4. UDP -> AtomicLoad::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.12.1.5. SC  -> AtomicLoad::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.12.1.6. SD  -> AtomicLoad::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.12.1.7. I   -> AtomicLoad::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.12.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.12.2.1. UC  -> AtomicLoad::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.12.2.2. UCE -> AtomicLoad::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.12.2.3. UD  -> AtomicLoad::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.12.2.4. UDP -> AtomicLoad::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.12.2.5. SC  -> AtomicLoad::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.12.2.6. SD  -> AtomicLoad::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.12.2.7. I   -> AtomicLoad::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.12.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.12.3.1. UC  -> AtomicLoad::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.12.3.2. UCE -> AtomicLoad::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.12.3.3. UD  -> AtomicLoad::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.12.3.4. UDP -> AtomicLoad::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.12.3.5. SC  -> AtomicLoad::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.12.3.6. SD  -> AtomicLoad::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.12.3.7. I   -> AtomicLoad::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.12.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.12.4.1. UC  -> AtomicLoad::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.12.4.2. UCE -> AtomicLoad::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.12.4.3. UD  -> AtomicLoad::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.12.4.4. UDP -> AtomicLoad::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.12.4.5. SC  -> AtomicLoad::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.12.4.6. SD  -> AtomicLoad::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.12.4.7. I   -> AtomicLoad::SET ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.12.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.12.5.1. UC  -> AtomicLoad::SET ", Xact::CacheStates::UC , true )
                ->Leaf("### D.12.5.2. UCE -> AtomicLoad::SET ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.12.5.3. UD  -> AtomicLoad::SET ", Xact::CacheStates::UD , true )
                ->Leaf("### D.12.5.4. UDP -> AtomicLoad::SET ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.12.5.5. SC  -> AtomicLoad::SET ", Xact::CacheStates::SC , true )
                ->Leaf("### D.12.5.6. SD  -> AtomicLoad::SET ", Xact::CacheStates::SD , true )
                ->Leaf("### D.12.5.7. I   -> AtomicLoad::SET ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.13. Initial state of AtomicLoad::SMAX", Opcodes::REQ::AtomicLoad::SMAX)

            ->ForkSilentTransitions("## D.13.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.13.1.1. UC  -> AtomicLoad::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.13.1.2. UCE -> AtomicLoad::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.13.1.3. UD  -> AtomicLoad::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.13.1.4. UDP -> AtomicLoad::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.13.1.5. SC  -> AtomicLoad::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.13.1.6. SD  -> AtomicLoad::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.13.1.7. I   -> AtomicLoad::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.13.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.13.2.1. UC  -> AtomicLoad::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.13.2.2. UCE -> AtomicLoad::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.13.2.3. UD  -> AtomicLoad::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.13.2.4. UDP -> AtomicLoad::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.13.2.5. SC  -> AtomicLoad::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.13.2.6. SD  -> AtomicLoad::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.13.2.7. I   -> AtomicLoad::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.13.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.13.3.1. UC  -> AtomicLoad::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.13.3.2. UCE -> AtomicLoad::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.13.3.3. UD  -> AtomicLoad::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.13.3.4. UDP -> AtomicLoad::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.13.3.5. SC  -> AtomicLoad::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.13.3.6. SD  -> AtomicLoad::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.13.3.7. I   -> AtomicLoad::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.13.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.13.4.1. UC  -> AtomicLoad::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.13.4.2. UCE -> AtomicLoad::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.13.4.3. UD  -> AtomicLoad::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.13.4.4. UDP -> AtomicLoad::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.13.4.5. SC  -> AtomicLoad::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.13.4.6. SD  -> AtomicLoad::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.13.4.7. I   -> AtomicLoad::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.13.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.13.5.1. UC  -> AtomicLoad::SMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.13.5.2. UCE -> AtomicLoad::SMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.13.5.3. UD  -> AtomicLoad::SMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.13.5.4. UDP -> AtomicLoad::SMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.13.5.5. SC  -> AtomicLoad::SMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.13.5.6. SD  -> AtomicLoad::SMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.13.5.7. I   -> AtomicLoad::SMAX ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.14. Initial state of AtomicLoad::SMIN", Opcodes::REQ::AtomicLoad::SMIN)

            ->ForkSilentTransitions("## D.14.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.14.1.1. UC  -> AtomicLoad::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.14.1.2. UCE -> AtomicLoad::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.14.1.3. UD  -> AtomicLoad::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.14.1.4. UDP -> AtomicLoad::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.14.1.5. SC  -> AtomicLoad::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.14.1.6. SD  -> AtomicLoad::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.14.1.7. I   -> AtomicLoad::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.14.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.14.2.1. UC  -> AtomicLoad::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.14.2.2. UCE -> AtomicLoad::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.14.2.3. UD  -> AtomicLoad::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.14.2.4. UDP -> AtomicLoad::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.14.2.5. SC  -> AtomicLoad::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.14.2.6. SD  -> AtomicLoad::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.14.2.7. I   -> AtomicLoad::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.14.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.14.3.1. UC  -> AtomicLoad::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.14.3.2. UCE -> AtomicLoad::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.14.3.3. UD  -> AtomicLoad::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.14.3.4. UDP -> AtomicLoad::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.14.3.5. SC  -> AtomicLoad::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.14.3.6. SD  -> AtomicLoad::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.14.3.7. I   -> AtomicLoad::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.14.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.14.4.1. UC  -> AtomicLoad::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.14.4.2. UCE -> AtomicLoad::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.14.4.3. UD  -> AtomicLoad::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.14.4.4. UDP -> AtomicLoad::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.14.4.5. SC  -> AtomicLoad::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.14.4.6. SD  -> AtomicLoad::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.14.4.7. I   -> AtomicLoad::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.14.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.14.5.1. UC  -> AtomicLoad::SMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.14.5.2. UCE -> AtomicLoad::SMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.14.5.3. UD  -> AtomicLoad::SMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.14.5.4. UDP -> AtomicLoad::SMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.14.5.5. SC  -> AtomicLoad::SMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.14.5.6. SD  -> AtomicLoad::SMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.14.5.7. I   -> AtomicLoad::SMIN ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.15. Initial state of AtomicLoad::UMAX", Opcodes::REQ::AtomicLoad::UMAX)

            ->ForkSilentTransitions("## D.15.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.15.1.1. UC  -> AtomicLoad::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.15.1.2. UCE -> AtomicLoad::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.15.1.3. UD  -> AtomicLoad::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.15.1.4. UDP -> AtomicLoad::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.15.1.5. SC  -> AtomicLoad::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.15.1.6. SD  -> AtomicLoad::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.15.1.7. I   -> AtomicLoad::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.15.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.15.2.1. UC  -> AtomicLoad::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.15.2.2. UCE -> AtomicLoad::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.15.2.3. UD  -> AtomicLoad::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.15.2.4. UDP -> AtomicLoad::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.15.2.5. SC  -> AtomicLoad::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.15.2.6. SD  -> AtomicLoad::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.15.2.7. I   -> AtomicLoad::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.15.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.15.3.1. UC  -> AtomicLoad::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.15.3.2. UCE -> AtomicLoad::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.15.3.3. UD  -> AtomicLoad::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.15.3.4. UDP -> AtomicLoad::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.15.3.5. SC  -> AtomicLoad::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.15.3.6. SD  -> AtomicLoad::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.15.3.7. I   -> AtomicLoad::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.15.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.15.4.1. UC  -> AtomicLoad::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.15.4.2. UCE -> AtomicLoad::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.15.4.3. UD  -> AtomicLoad::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.15.4.4. UDP -> AtomicLoad::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.15.4.5. SC  -> AtomicLoad::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.15.4.6. SD  -> AtomicLoad::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.15.4.7. I   -> AtomicLoad::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.15.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.15.5.1. UC  -> AtomicLoad::UMAX ", Xact::CacheStates::UC , true )
                ->Leaf("### D.15.5.2. UCE -> AtomicLoad::UMAX ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.15.5.3. UD  -> AtomicLoad::UMAX ", Xact::CacheStates::UD , true )
                ->Leaf("### D.15.5.4. UDP -> AtomicLoad::UMAX ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.15.5.5. SC  -> AtomicLoad::UMAX ", Xact::CacheStates::SC , true )
                ->Leaf("### D.15.5.6. SD  -> AtomicLoad::UMAX ", Xact::CacheStates::SD , true )
                ->Leaf("### D.15.5.7. I   -> AtomicLoad::UMAX ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.16. Initial state of AtomicLoad::UMIN", Opcodes::REQ::AtomicLoad::UMIN)

            ->ForkSilentTransitions("## D.16.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.16.1.1. UC  -> AtomicLoad::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.16.1.2. UCE -> AtomicLoad::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.16.1.3. UD  -> AtomicLoad::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.16.1.4. UDP -> AtomicLoad::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.16.1.5. SC  -> AtomicLoad::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.16.1.6. SD  -> AtomicLoad::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.16.1.7. I   -> AtomicLoad::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.16.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.16.2.1. UC  -> AtomicLoad::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.16.2.2. UCE -> AtomicLoad::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.16.2.3. UD  -> AtomicLoad::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.16.2.4. UDP -> AtomicLoad::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.16.2.5. SC  -> AtomicLoad::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.16.2.6. SD  -> AtomicLoad::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.16.2.7. I   -> AtomicLoad::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.16.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.16.3.1. UC  -> AtomicLoad::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.16.3.2. UCE -> AtomicLoad::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.16.3.3. UD  -> AtomicLoad::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.16.3.4. UDP -> AtomicLoad::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.16.3.5. SC  -> AtomicLoad::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.16.3.6. SD  -> AtomicLoad::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.16.3.7. I   -> AtomicLoad::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.16.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.16.4.1. UC  -> AtomicLoad::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.16.4.2. UCE -> AtomicLoad::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.16.4.3. UD  -> AtomicLoad::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.16.4.4. UDP -> AtomicLoad::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.16.4.5. SC  -> AtomicLoad::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.16.4.6. SD  -> AtomicLoad::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.16.4.7. I   -> AtomicLoad::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.16.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.16.5.1. UC  -> AtomicLoad::UMIN ", Xact::CacheStates::UC , true )
                ->Leaf("### D.16.5.2. UCE -> AtomicLoad::UMIN ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.16.5.3. UD  -> AtomicLoad::UMIN ", Xact::CacheStates::UD , true )
                ->Leaf("### D.16.5.4. UDP -> AtomicLoad::UMIN ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.16.5.5. SC  -> AtomicLoad::UMIN ", Xact::CacheStates::SC , true )
                ->Leaf("### D.16.5.6. SD  -> AtomicLoad::UMIN ", Xact::CacheStates::SD , true )
                ->Leaf("### D.16.5.7. I   -> AtomicLoad::UMIN ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.17. Initial state of AtomicSwap", Opcodes::REQ::AtomicSwap)

            ->ForkSilentTransitions("## D.17.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.17.1.1. UC  -> AtomicSwap ", Xact::CacheStates::UC , true )
                ->Leaf("### D.17.1.2. UCE -> AtomicSwap ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.17.1.3. UD  -> AtomicSwap ", Xact::CacheStates::UD , true )
                ->Leaf("### D.17.1.4. UDP -> AtomicSwap ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.17.1.5. SC  -> AtomicSwap ", Xact::CacheStates::SC , true )
                ->Leaf("### D.17.1.6. SD  -> AtomicSwap ", Xact::CacheStates::SD , true )
                ->Leaf("### D.17.1.7. I   -> AtomicSwap ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.17.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.17.2.1. UC  -> AtomicSwap ", Xact::CacheStates::UC , true )
                ->Leaf("### D.17.2.2. UCE -> AtomicSwap ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.17.2.3. UD  -> AtomicSwap ", Xact::CacheStates::UD , true )
                ->Leaf("### D.17.2.4. UDP -> AtomicSwap ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.17.2.5. SC  -> AtomicSwap ", Xact::CacheStates::SC , true )
                ->Leaf("### D.17.2.6. SD  -> AtomicSwap ", Xact::CacheStates::SD , true )
                ->Leaf("### D.17.2.7. I   -> AtomicSwap ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.17.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.17.3.1. UC  -> AtomicSwap ", Xact::CacheStates::UC , true )
                ->Leaf("### D.17.3.2. UCE -> AtomicSwap ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.17.3.3. UD  -> AtomicSwap ", Xact::CacheStates::UD , true )
                ->Leaf("### D.17.3.4. UDP -> AtomicSwap ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.17.3.5. SC  -> AtomicSwap ", Xact::CacheStates::SC , true )
                ->Leaf("### D.17.3.6. SD  -> AtomicSwap ", Xact::CacheStates::SD , true )
                ->Leaf("### D.17.3.7. I   -> AtomicSwap ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.17.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.17.4.1. UC  -> AtomicSwap ", Xact::CacheStates::UC , true )
                ->Leaf("### D.17.4.2. UCE -> AtomicSwap ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.17.4.3. UD  -> AtomicSwap ", Xact::CacheStates::UD , true )
                ->Leaf("### D.17.4.4. UDP -> AtomicSwap ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.17.4.5. SC  -> AtomicSwap ", Xact::CacheStates::SC , true )
                ->Leaf("### D.17.4.6. SD  -> AtomicSwap ", Xact::CacheStates::SD , true )
                ->Leaf("### D.17.4.7. I   -> AtomicSwap ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.17.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.17.5.1. UC  -> AtomicSwap ", Xact::CacheStates::UC , true )
                ->Leaf("### D.17.5.2. UCE -> AtomicSwap ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.17.5.3. UD  -> AtomicSwap ", Xact::CacheStates::UD , true )
                ->Leaf("### D.17.5.4. UDP -> AtomicSwap ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.17.5.5. SC  -> AtomicSwap ", Xact::CacheStates::SC , true )
                ->Leaf("### D.17.5.6. SD  -> AtomicSwap ", Xact::CacheStates::SD , true )
                ->Leaf("### D.17.5.7. I   -> AtomicSwap ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt D.18. Initial state of AtomicCompare", Opcodes::REQ::AtomicCompare)

            ->ForkSilentTransitions("## D.18.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### D.18.1.1. UC  -> AtomicCompare ", Xact::CacheStates::UC , true )
                ->Leaf("### D.18.1.2. UCE -> AtomicCompare ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.18.1.3. UD  -> AtomicCompare ", Xact::CacheStates::UD , true )
                ->Leaf("### D.18.1.4. UDP -> AtomicCompare ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.18.1.5. SC  -> AtomicCompare ", Xact::CacheStates::SC , true )
                ->Leaf("### D.18.1.6. SD  -> AtomicCompare ", Xact::CacheStates::SD , true )
                ->Leaf("### D.18.1.7. I   -> AtomicCompare ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.18.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### D.18.2.1. UC  -> AtomicCompare ", Xact::CacheStates::UC , true )
                ->Leaf("### D.18.2.2. UCE -> AtomicCompare ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.18.2.3. UD  -> AtomicCompare ", Xact::CacheStates::UD , true )
                ->Leaf("### D.18.2.4. UDP -> AtomicCompare ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.18.2.5. SC  -> AtomicCompare ", Xact::CacheStates::SC , true )
                ->Leaf("### D.18.2.6. SD  -> AtomicCompare ", Xact::CacheStates::SD , true )
                ->Leaf("### D.18.2.7. I   -> AtomicCompare ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.18.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### D.18.3.1. UC  -> AtomicCompare ", Xact::CacheStates::UC , true )
                ->Leaf("### D.18.3.2. UCE -> AtomicCompare ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.18.3.3. UD  -> AtomicCompare ", Xact::CacheStates::UD , true )
                ->Leaf("### D.18.3.4. UDP -> AtomicCompare ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.18.3.5. SC  -> AtomicCompare ", Xact::CacheStates::SC , true )
                ->Leaf("### D.18.3.6. SD  -> AtomicCompare ", Xact::CacheStates::SD , true )
                ->Leaf("### D.18.3.7. I   -> AtomicCompare ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.18.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### D.18.4.1. UC  -> AtomicCompare ", Xact::CacheStates::UC , true )
                ->Leaf("### D.18.4.2. UCE -> AtomicCompare ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.18.4.3. UD  -> AtomicCompare ", Xact::CacheStates::UD , true )
                ->Leaf("### D.18.4.4. UDP -> AtomicCompare ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.18.4.5. SC  -> AtomicCompare ", Xact::CacheStates::SC , true )
                ->Leaf("### D.18.4.6. SD  -> AtomicCompare ", Xact::CacheStates::SD , true )
                ->Leaf("### D.18.4.7. I   -> AtomicCompare ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## D.18.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### D.18.5.1. UC  -> AtomicCompare ", Xact::CacheStates::UC , true )
                ->Leaf("### D.18.5.2. UCE -> AtomicCompare ", Xact::CacheStates::UCE, true )
                ->Leaf("### D.18.5.3. UD  -> AtomicCompare ", Xact::CacheStates::UD , true )
                ->Leaf("### D.18.5.4. UDP -> AtomicCompare ", Xact::CacheStates::UDP, true )
                ->Leaf("### D.18.5.5. SC  -> AtomicCompare ", Xact::CacheStates::SC , true )
                ->Leaf("### D.18.5.6. SD  -> AtomicCompare ", Xact::CacheStates::SD , true )
                ->Leaf("### D.18.5.7. I   -> AtomicCompare ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial->End();
    tcptInitial = nullptr;
}

#endif
