#include "tc_common_initial.hpp"        // IWYU pragma: keep
#include "tcpt_c_initial_write.hpp"     // IWYU pragma: keep

#ifdef CHI_ISSUE_E

void TCPtCInitialWrite(
    size_t*                     totalCount,
    size_t*                     errCountFail,
    size_t*                     errCountEnvError,
    std::vector<std::string>*   errList,
    const Xact::Topology&       topo) noexcept
{
    TCPtInitial* tcptInitial = (new TCPtInitial())
        ->TotalCount(totalCount)
        ->ErrCountFail(errCountFail)
        ->ErrCountEnvError(errCountEnvError)
        ->ErrList(errList)
        ->Topology(topo)
        ->Begin();

    tcptInitial
        ->ForkREQ("# TCPt C.1. Initial state of WriteNoSnpFull", Opcodes::REQ::WriteNoSnpFull)

            ->ForkSilentTransitions("## C.1.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.1.1.1. UC  -> WriteNoSnpFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.1.1.2. UCE -> WriteNoSnpFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.1.1.3. UD  -> WriteNoSnpFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.1.1.4. UDP -> WriteNoSnpFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.1.1.5. SC  -> WriteNoSnpFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.1.1.6. SD  -> WriteNoSnpFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.1.1.7. I   -> WriteNoSnpFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.1.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.1.2.1. UC  -> WriteNoSnpFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.1.2.2. UCE -> WriteNoSnpFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.1.2.3. UD  -> WriteNoSnpFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.1.2.4. UDP -> WriteNoSnpFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.1.2.5. SC  -> WriteNoSnpFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.1.2.6. SD  -> WriteNoSnpFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.1.2.7. I   -> WriteNoSnpFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.1.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.1.3.1. UC  -> WriteNoSnpFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.1.3.2. UCE -> WriteNoSnpFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.1.3.3. UD  -> WriteNoSnpFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.1.3.4. UDP -> WriteNoSnpFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.1.3.5. SC  -> WriteNoSnpFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.1.3.6. SD  -> WriteNoSnpFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.1.3.7. I   -> WriteNoSnpFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.1.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.1.4.1. UC  -> WriteNoSnpFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.1.4.2. UCE -> WriteNoSnpFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.1.4.3. UD  -> WriteNoSnpFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.1.4.4. UDP -> WriteNoSnpFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.1.4.5. SC  -> WriteNoSnpFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.1.4.6. SD  -> WriteNoSnpFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.1.4.7. I   -> WriteNoSnpFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.1.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.1.5.1. UC  -> WriteNoSnpFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.1.5.2. UCE -> WriteNoSnpFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.1.5.3. UD  -> WriteNoSnpFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.1.5.4. UDP -> WriteNoSnpFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.1.5.5. SC  -> WriteNoSnpFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.1.5.6. SD  -> WriteNoSnpFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.1.5.7. I   -> WriteNoSnpFull ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.2. Initial state of WriteNoSnpPtl", Opcodes::REQ::WriteNoSnpPtl)

            ->ForkSilentTransitions("## C.2.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.2.1.1. UC  -> WriteNoSnpPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.2.1.2. UCE -> WriteNoSnpPtl ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.2.1.3. UD  -> WriteNoSnpPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.2.1.4. UDP -> WriteNoSnpPtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.2.1.5. SC  -> WriteNoSnpPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.2.1.6. SD  -> WriteNoSnpPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.2.1.7. I   -> WriteNoSnpPtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.2.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.2.2.1. UC  -> WriteNoSnpPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.2.2.2. UCE -> WriteNoSnpPtl ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.2.2.3. UD  -> WriteNoSnpPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.2.2.4. UDP -> WriteNoSnpPtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.2.2.5. SC  -> WriteNoSnpPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.2.2.6. SD  -> WriteNoSnpPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.2.2.7. I   -> WriteNoSnpPtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.2.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.2.3.1. UC  -> WriteNoSnpPtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.2.3.2. UCE -> WriteNoSnpPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.2.3.3. UD  -> WriteNoSnpPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.2.3.4. UDP -> WriteNoSnpPtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.2.3.5. SC  -> WriteNoSnpPtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.2.3.6. SD  -> WriteNoSnpPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.2.3.7. I   -> WriteNoSnpPtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.2.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.2.4.1. UC  -> WriteNoSnpPtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.2.4.2. UCE -> WriteNoSnpPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.2.4.3. UD  -> WriteNoSnpPtl ", Xact::CacheStates::UD , true )
                ->Leaf("### C.2.4.4. UDP -> WriteNoSnpPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.2.4.5. SC  -> WriteNoSnpPtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.2.4.6. SD  -> WriteNoSnpPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.2.4.7. I   -> WriteNoSnpPtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.2.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.2.5.1. UC  -> WriteNoSnpPtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.2.5.2. UCE -> WriteNoSnpPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.2.5.3. UD  -> WriteNoSnpPtl ", Xact::CacheStates::UD , true )
                ->Leaf("### C.2.5.4. UDP -> WriteNoSnpPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.2.5.5. SC  -> WriteNoSnpPtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.2.5.6. SD  -> WriteNoSnpPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.2.5.7. I   -> WriteNoSnpPtl ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.3. Initial state of WriteNoSnpZero", Opcodes::REQ::WriteNoSnpZero)

            ->ForkSilentTransitions("## C.3.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.3.1.1. UC  -> WriteNoSnpZero ", Xact::CacheStates::UC , false)
                ->Leaf("### C.3.1.2. UCE -> WriteNoSnpZero ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.3.1.3. UD  -> WriteNoSnpZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.3.1.4. UDP -> WriteNoSnpZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.3.1.5. SC  -> WriteNoSnpZero ", Xact::CacheStates::SC , false)
                ->Leaf("### C.3.1.6. SD  -> WriteNoSnpZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.3.1.7. I   -> WriteNoSnpZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.3.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.3.2.1. UC  -> WriteNoSnpZero ", Xact::CacheStates::UC , false)
                ->Leaf("### C.3.2.2. UCE -> WriteNoSnpZero ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.3.2.3. UD  -> WriteNoSnpZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.3.2.4. UDP -> WriteNoSnpZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.3.2.5. SC  -> WriteNoSnpZero ", Xact::CacheStates::SC , false)
                ->Leaf("### C.3.2.6. SD  -> WriteNoSnpZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.3.2.7. I   -> WriteNoSnpZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.3.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.3.3.1. UC  -> WriteNoSnpZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.3.3.2. UCE -> WriteNoSnpZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.3.3.3. UD  -> WriteNoSnpZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.3.3.4. UDP -> WriteNoSnpZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.3.3.5. SC  -> WriteNoSnpZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.3.3.6. SD  -> WriteNoSnpZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.3.3.7. I   -> WriteNoSnpZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.3.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.3.4.1. UC  -> WriteNoSnpZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.3.4.2. UCE -> WriteNoSnpZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.3.4.3. UD  -> WriteNoSnpZero ", Xact::CacheStates::UD , true )
                ->Leaf("### C.3.4.4. UDP -> WriteNoSnpZero ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.3.4.5. SC  -> WriteNoSnpZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.3.4.6. SD  -> WriteNoSnpZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.3.4.7. I   -> WriteNoSnpZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.3.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.3.5.1. UC  -> WriteNoSnpZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.3.5.2. UCE -> WriteNoSnpZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.3.5.3. UD  -> WriteNoSnpZero ", Xact::CacheStates::UD , true )
                ->Leaf("### C.3.5.4. UDP -> WriteNoSnpZero ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.3.5.5. SC  -> WriteNoSnpZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.3.5.6. SD  -> WriteNoSnpZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.3.5.7. I   -> WriteNoSnpZero ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.4. Initial state of WriteUniqueFull", Opcodes::REQ::WriteUniqueFull)

            ->ForkSilentTransitions("## C.4.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.4.1.1. UC  -> WriteUniqueFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.4.1.2. UCE -> WriteUniqueFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.4.1.3. UD  -> WriteUniqueFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.4.1.4. UDP -> WriteUniqueFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.4.1.5. SC  -> WriteUniqueFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.4.1.6. SD  -> WriteUniqueFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.4.1.7. I   -> WriteUniqueFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.4.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.4.2.1. UC  -> WriteUniqueFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.4.2.2. UCE -> WriteUniqueFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.4.2.3. UD  -> WriteUniqueFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.4.2.4. UDP -> WriteUniqueFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.4.2.5. SC  -> WriteUniqueFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.4.2.6. SD  -> WriteUniqueFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.4.2.7. I   -> WriteUniqueFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.4.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.4.3.1. UC  -> WriteUniqueFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.4.3.2. UCE -> WriteUniqueFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.4.3.3. UD  -> WriteUniqueFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.4.3.4. UDP -> WriteUniqueFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.4.3.5. SC  -> WriteUniqueFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.4.3.6. SD  -> WriteUniqueFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.4.3.7. I   -> WriteUniqueFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.4.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.4.4.1. UC  -> WriteUniqueFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.4.4.2. UCE -> WriteUniqueFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.4.4.3. UD  -> WriteUniqueFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.4.4.4. UDP -> WriteUniqueFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.4.4.5. SC  -> WriteUniqueFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.4.4.6. SD  -> WriteUniqueFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.4.4.7. I   -> WriteUniqueFull ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.4.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.4.5.1. UC  -> WriteUniqueFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.4.5.2. UCE -> WriteUniqueFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.4.5.3. UD  -> WriteUniqueFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.4.5.4. UDP -> WriteUniqueFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.4.5.5. SC  -> WriteUniqueFull ", Xact::CacheStates::SC , true )
                ->Leaf("### C.4.5.6. SD  -> WriteUniqueFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.4.5.7. I   -> WriteUniqueFull ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.5. Initial state of WriteUniquePtl", Opcodes::REQ::WriteUniquePtl)

            ->ForkSilentTransitions("## C.5.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.5.1.1. UC  -> WriteUniquePtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.5.1.2. UCE -> WriteUniquePtl ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.5.1.3. UD  -> WriteUniquePtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.5.1.4. UDP -> WriteUniquePtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.5.1.5. SC  -> WriteUniquePtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.5.1.6. SD  -> WriteUniquePtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.5.1.7. I   -> WriteUniquePtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.5.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.5.2.1. UC  -> WriteUniquePtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.5.2.2. UCE -> WriteUniquePtl ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.5.2.3. UD  -> WriteUniquePtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.5.2.4. UDP -> WriteUniquePtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.5.2.5. SC  -> WriteUniquePtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.5.2.6. SD  -> WriteUniquePtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.5.2.7. I   -> WriteUniquePtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.5.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.5.3.1. UC  -> WriteUniquePtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.5.3.2. UCE -> WriteUniquePtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.5.3.3. UD  -> WriteUniquePtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.5.3.4. UDP -> WriteUniquePtl ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.5.3.5. SC  -> WriteUniquePtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.5.3.6. SD  -> WriteUniquePtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.5.3.7. I   -> WriteUniquePtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.5.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.5.4.1. UC  -> WriteUniquePtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.5.4.2. UCE -> WriteUniquePtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.5.4.3. UD  -> WriteUniquePtl ", Xact::CacheStates::UD , true )
                ->Leaf("### C.5.4.4. UDP -> WriteUniquePtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.5.4.5. SC  -> WriteUniquePtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.5.4.6. SD  -> WriteUniquePtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.5.4.7. I   -> WriteUniquePtl ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.5.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.5.5.1. UC  -> WriteUniquePtl ", Xact::CacheStates::UC , true )
                ->Leaf("### C.5.5.2. UCE -> WriteUniquePtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.5.5.3. UD  -> WriteUniquePtl ", Xact::CacheStates::UD , true )
                ->Leaf("### C.5.5.4. UDP -> WriteUniquePtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.5.5.5. SC  -> WriteUniquePtl ", Xact::CacheStates::SC , true )
                ->Leaf("### C.5.5.6. SD  -> WriteUniquePtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.5.5.7. I   -> WriteUniquePtl ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.6. Initial state of WriteUniqueZero", Opcodes::REQ::WriteUniqueZero)

            ->ForkSilentTransitions("## C.6.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.6.1.1. UC  -> WriteUniqueZero ", Xact::CacheStates::UC , false)
                ->Leaf("### C.6.1.2. UCE -> WriteUniqueZero ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.6.1.3. UD  -> WriteUniqueZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.6.1.4. UDP -> WriteUniqueZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.6.1.5. SC  -> WriteUniqueZero ", Xact::CacheStates::SC , false)
                ->Leaf("### C.6.1.6. SD  -> WriteUniqueZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.6.1.7. I   -> WriteUniqueZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.6.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.6.2.1. UC  -> WriteUniqueZero ", Xact::CacheStates::UC , false)
                ->Leaf("### C.6.2.2. UCE -> WriteUniqueZero ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.6.2.3. UD  -> WriteUniqueZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.6.2.4. UDP -> WriteUniqueZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.6.2.5. SC  -> WriteUniqueZero ", Xact::CacheStates::SC , false)
                ->Leaf("### C.6.2.6. SD  -> WriteUniqueZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.6.2.7. I   -> WriteUniqueZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.6.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.6.3.1. UC  -> WriteUniqueZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.6.3.2. UCE -> WriteUniqueZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.6.3.3. UD  -> WriteUniqueZero ", Xact::CacheStates::UD , false)
                ->Leaf("### C.6.3.4. UDP -> WriteUniqueZero ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.6.3.5. SC  -> WriteUniqueZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.6.3.6. SD  -> WriteUniqueZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.6.3.7. I   -> WriteUniqueZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.6.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.6.4.1. UC  -> WriteUniqueZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.6.4.2. UCE -> WriteUniqueZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.6.4.3. UD  -> WriteUniqueZero ", Xact::CacheStates::UD , true )
                ->Leaf("### C.6.4.4. UDP -> WriteUniqueZero ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.6.4.5. SC  -> WriteUniqueZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.6.4.6. SD  -> WriteUniqueZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.6.4.7. I   -> WriteUniqueZero ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.6.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.6.5.1. UC  -> WriteUniqueZero ", Xact::CacheStates::UC , true )
                ->Leaf("### C.6.5.2. UCE -> WriteUniqueZero ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.6.5.3. UD  -> WriteUniqueZero ", Xact::CacheStates::UD , true )
                ->Leaf("### C.6.5.4. UDP -> WriteUniqueZero ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.6.5.5. SC  -> WriteUniqueZero ", Xact::CacheStates::SC , true )
                ->Leaf("### C.6.5.6. SD  -> WriteUniqueZero ", Xact::CacheStates::SD , false)
                ->Leaf("### C.6.5.7. I   -> WriteUniqueZero ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.7. Initial state of WriteUniqueFullStash", Opcodes::REQ::WriteUniqueFullStash)

            ->ForkSilentTransitions("## C.7.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.7.1.1. UC  -> WriteUniqueFullStash ", Xact::CacheStates::UC , false)
                ->Leaf("### C.7.1.2. UCE -> WriteUniqueFullStash ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.7.1.3. UD  -> WriteUniqueFullStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.7.1.4. UDP -> WriteUniqueFullStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.7.1.5. SC  -> WriteUniqueFullStash ", Xact::CacheStates::SC , false)
                ->Leaf("### C.7.1.6. SD  -> WriteUniqueFullStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.7.1.7. I   -> WriteUniqueFullStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.7.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.7.2.1. UC  -> WriteUniqueFullStash ", Xact::CacheStates::UC , false)
                ->Leaf("### C.7.2.2. UCE -> WriteUniqueFullStash ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.7.2.3. UD  -> WriteUniqueFullStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.7.2.4. UDP -> WriteUniqueFullStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.7.2.5. SC  -> WriteUniqueFullStash ", Xact::CacheStates::SC , false)
                ->Leaf("### C.7.2.6. SD  -> WriteUniqueFullStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.7.2.7. I   -> WriteUniqueFullStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.7.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.7.3.1. UC  -> WriteUniqueFullStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.7.3.2. UCE -> WriteUniqueFullStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.7.3.3. UD  -> WriteUniqueFullStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.7.3.4. UDP -> WriteUniqueFullStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.7.3.5. SC  -> WriteUniqueFullStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.7.3.6. SD  -> WriteUniqueFullStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.7.3.7. I   -> WriteUniqueFullStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.7.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.7.4.1. UC  -> WriteUniqueFullStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.7.4.2. UCE -> WriteUniqueFullStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.7.4.3. UD  -> WriteUniqueFullStash ", Xact::CacheStates::UD , true )
                ->Leaf("### C.7.4.4. UDP -> WriteUniqueFullStash ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.7.4.5. SC  -> WriteUniqueFullStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.7.4.6. SD  -> WriteUniqueFullStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.7.4.7. I   -> WriteUniqueFullStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.7.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.7.5.1. UC  -> WriteUniqueFullStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.7.5.2. UCE -> WriteUniqueFullStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.7.5.3. UD  -> WriteUniqueFullStash ", Xact::CacheStates::UD , true )
                ->Leaf("### C.7.5.4. UDP -> WriteUniqueFullStash ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.7.5.5. SC  -> WriteUniqueFullStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.7.5.6. SD  -> WriteUniqueFullStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.7.5.7. I   -> WriteUniqueFullStash ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.8. Initial state of WriteUniquePtlStash", Opcodes::REQ::WriteUniquePtlStash)

            ->ForkSilentTransitions("## C.8.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.8.1.1. UC  -> WriteUniquePtlStash ", Xact::CacheStates::UC , false)
                ->Leaf("### C.8.1.2. UCE -> WriteUniquePtlStash ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.8.1.3. UD  -> WriteUniquePtlStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.8.1.4. UDP -> WriteUniquePtlStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.8.1.5. SC  -> WriteUniquePtlStash ", Xact::CacheStates::SC , false)
                ->Leaf("### C.8.1.6. SD  -> WriteUniquePtlStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.8.1.7. I   -> WriteUniquePtlStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.8.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.8.2.1. UC  -> WriteUniquePtlStash ", Xact::CacheStates::UC , false)
                ->Leaf("### C.8.2.2. UCE -> WriteUniquePtlStash ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.8.2.3. UD  -> WriteUniquePtlStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.8.2.4. UDP -> WriteUniquePtlStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.8.2.5. SC  -> WriteUniquePtlStash ", Xact::CacheStates::SC , false)
                ->Leaf("### C.8.2.6. SD  -> WriteUniquePtlStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.8.2.7. I   -> WriteUniquePtlStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.8.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.8.3.1. UC  -> WriteUniquePtlStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.8.3.2. UCE -> WriteUniquePtlStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.8.3.3. UD  -> WriteUniquePtlStash ", Xact::CacheStates::UD , false)
                ->Leaf("### C.8.3.4. UDP -> WriteUniquePtlStash ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.8.3.5. SC  -> WriteUniquePtlStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.8.3.6. SD  -> WriteUniquePtlStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.8.3.7. I   -> WriteUniquePtlStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.8.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.8.4.1. UC  -> WriteUniquePtlStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.8.4.2. UCE -> WriteUniquePtlStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.8.4.3. UD  -> WriteUniquePtlStash ", Xact::CacheStates::UD , true )
                ->Leaf("### C.8.4.4. UDP -> WriteUniquePtlStash ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.8.4.5. SC  -> WriteUniquePtlStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.8.4.6. SD  -> WriteUniquePtlStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.8.4.7. I   -> WriteUniquePtlStash ", Xact::CacheStates::I  , true )
            ->Rest()

            ->ForkSilentTransitions("## C.8.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.8.5.1. UC  -> WriteUniquePtlStash ", Xact::CacheStates::UC , true )
                ->Leaf("### C.8.5.2. UCE -> WriteUniquePtlStash ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.8.5.3. UD  -> WriteUniquePtlStash ", Xact::CacheStates::UD , true )
                ->Leaf("### C.8.5.4. UDP -> WriteUniquePtlStash ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.8.5.5. SC  -> WriteUniquePtlStash ", Xact::CacheStates::SC , true )
                ->Leaf("### C.8.5.6. SD  -> WriteUniquePtlStash ", Xact::CacheStates::SD , false)
                ->Leaf("### C.8.5.7. I   -> WriteUniquePtlStash ", Xact::CacheStates::I  , true )
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.9. Initial state of WriteBackFull", Opcodes::REQ::WriteBackFull)

            ->ForkSilentTransitions("## C.9.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.9.1.1. UC  -> WriteBackFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.9.1.2. UCE -> WriteBackFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.9.1.3. UD  -> WriteBackFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.9.1.4. UDP -> WriteBackFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.9.1.5. SC  -> WriteBackFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.9.1.6. SD  -> WriteBackFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.9.1.7. I   -> WriteBackFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.9.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.9.2.1. UC  -> WriteBackFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.9.2.2. UCE -> WriteBackFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.9.2.3. UD  -> WriteBackFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.9.2.4. UDP -> WriteBackFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.9.2.5. SC  -> WriteBackFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.9.2.6. SD  -> WriteBackFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.9.2.7. I   -> WriteBackFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.9.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.9.3.1. UC  -> WriteBackFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.9.3.2. UCE -> WriteBackFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.9.3.3. UD  -> WriteBackFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.9.3.4. UDP -> WriteBackFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.9.3.5. SC  -> WriteBackFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.9.3.6. SD  -> WriteBackFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.9.3.7. I   -> WriteBackFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.9.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.9.4.1. UC  -> WriteBackFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.9.4.2. UCE -> WriteBackFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.9.4.3. UD  -> WriteBackFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.9.4.4. UDP -> WriteBackFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.9.4.5. SC  -> WriteBackFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.9.4.6. SD  -> WriteBackFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.9.4.7. I   -> WriteBackFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.9.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.9.5.1. UC  -> WriteBackFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.9.5.2. UCE -> WriteBackFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.9.5.3. UD  -> WriteBackFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.9.5.4. UDP -> WriteBackFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.9.5.5. SC  -> WriteBackFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.9.5.6. SD  -> WriteBackFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.9.5.7. I   -> WriteBackFull ", Xact::CacheStates::I  , false)
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.10. Initial state of WriteBackPtl", Opcodes::REQ::WriteBackPtl)

            ->ForkSilentTransitions("## C.10.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.10.1.1. UC  -> WriteBackPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.10.1.2. UCE -> WriteBackPtl ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.10.1.3. UD  -> WriteBackPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.10.1.4. UDP -> WriteBackPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.10.1.5. SC  -> WriteBackPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.10.1.6. SD  -> WriteBackPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.10.1.7. I   -> WriteBackPtl ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.10.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.10.2.1. UC  -> WriteBackPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.10.2.2. UCE -> WriteBackPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.10.2.3. UD  -> WriteBackPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.10.2.4. UDP -> WriteBackPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.10.2.5. SC  -> WriteBackPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.10.2.6. SD  -> WriteBackPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.10.2.7. I   -> WriteBackPtl ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.10.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.10.3.1. UC  -> WriteBackPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.10.3.2. UCE -> WriteBackPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.10.3.3. UD  -> WriteBackPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.10.3.4. UDP -> WriteBackPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.10.3.5. SC  -> WriteBackPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.10.3.6. SD  -> WriteBackPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.10.3.7. I   -> WriteBackPtl ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.10.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.10.4.1. UC  -> WriteBackPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.10.4.2. UCE -> WriteBackPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.10.4.3. UD  -> WriteBackPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.10.4.4. UDP -> WriteBackPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.10.4.5. SC  -> WriteBackPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.10.4.6. SD  -> WriteBackPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.10.4.7. I   -> WriteBackPtl ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.10.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.10.5.1. UC  -> WriteBackPtl ", Xact::CacheStates::UC , false)
                ->Leaf("### C.10.5.2. UCE -> WriteBackPtl ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.10.5.3. UD  -> WriteBackPtl ", Xact::CacheStates::UD , false)
                ->Leaf("### C.10.5.4. UDP -> WriteBackPtl ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.10.5.5. SC  -> WriteBackPtl ", Xact::CacheStates::SC , false)
                ->Leaf("### C.10.5.6. SD  -> WriteBackPtl ", Xact::CacheStates::SD , false)
                ->Leaf("### C.10.5.7. I   -> WriteBackPtl ", Xact::CacheStates::I  , false)
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.11. Initial state of WriteCleanFull", Opcodes::REQ::WriteCleanFull)

            ->ForkSilentTransitions("## C.11.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.11.1.1. UC  -> WriteCleanFull ", Xact::CacheStates::UC , false)
                ->Leaf("### C.11.1.2. UCE -> WriteCleanFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.11.1.3. UD  -> WriteCleanFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.11.1.4. UDP -> WriteCleanFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.11.1.5. SC  -> WriteCleanFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.11.1.6. SD  -> WriteCleanFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.11.1.7. I   -> WriteCleanFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.11.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.11.2.1. UC  -> WriteCleanFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.11.2.2. UCE -> WriteCleanFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.11.2.3. UD  -> WriteCleanFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.11.2.4. UDP -> WriteCleanFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.11.2.5. SC  -> WriteCleanFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.11.2.6. SD  -> WriteCleanFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.11.2.7. I   -> WriteCleanFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.11.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.11.3.1. UC  -> WriteCleanFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.11.3.2. UCE -> WriteCleanFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.11.3.3. UD  -> WriteCleanFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.11.3.4. UDP -> WriteCleanFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.11.3.5. SC  -> WriteCleanFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.11.3.6. SD  -> WriteCleanFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.11.3.7. I   -> WriteCleanFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.11.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.11.4.1. UC  -> WriteCleanFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.11.4.2. UCE -> WriteCleanFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.11.4.3. UD  -> WriteCleanFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.11.4.4. UDP -> WriteCleanFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.11.4.5. SC  -> WriteCleanFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.11.4.6. SD  -> WriteCleanFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.11.4.7. I   -> WriteCleanFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.11.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.11.5.1. UC  -> WriteCleanFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.11.5.2. UCE -> WriteCleanFull ", Xact::CacheStates::UCE, true )
                ->Leaf("### C.11.5.3. UD  -> WriteCleanFull ", Xact::CacheStates::UD , true )
                ->Leaf("### C.11.5.4. UDP -> WriteCleanFull ", Xact::CacheStates::UDP, true )
                ->Leaf("### C.11.5.5. SC  -> WriteCleanFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.11.5.6. SD  -> WriteCleanFull ", Xact::CacheStates::SD , true )
                ->Leaf("### C.11.5.7. I   -> WriteCleanFull ", Xact::CacheStates::I  , false)
            ->Rest()

        ->End();

    tcptInitial
        ->ForkREQ("# TCPt C.12. Initial state of WriteEvictFull", Opcodes::REQ::WriteEvictFull)

            ->ForkSilentTransitions("## C.12.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.12.1.1. UC  -> WriteEvictFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.12.1.2. UCE -> WriteEvictFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.12.1.3. UD  -> WriteEvictFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.12.1.4. UDP -> WriteEvictFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.12.1.5. SC  -> WriteEvictFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.12.1.6. SD  -> WriteEvictFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.12.1.7. I   -> WriteEvictFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.12.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.12.2.1. UC  -> WriteEvictFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.12.2.2. UCE -> WriteEvictFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.12.2.3. UD  -> WriteEvictFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.12.2.4. UDP -> WriteEvictFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.12.2.5. SC  -> WriteEvictFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.12.2.6. SD  -> WriteEvictFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.12.2.7. I   -> WriteEvictFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.12.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.12.3.1. UC  -> WriteEvictFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.12.3.2. UCE -> WriteEvictFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.12.3.3. UD  -> WriteEvictFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.12.3.4. UDP -> WriteEvictFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.12.3.5. SC  -> WriteEvictFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.12.3.6. SD  -> WriteEvictFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.12.3.7. I   -> WriteEvictFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.12.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.12.4.1. UC  -> WriteEvictFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.12.4.2. UCE -> WriteEvictFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.12.4.3. UD  -> WriteEvictFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.12.4.4. UDP -> WriteEvictFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.12.4.5. SC  -> WriteEvictFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.12.4.6. SD  -> WriteEvictFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.12.4.7. I   -> WriteEvictFull ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.12.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.12.5.1. UC  -> WriteEvictFull ", Xact::CacheStates::UC , true )
                ->Leaf("### C.12.5.2. UCE -> WriteEvictFull ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.12.5.3. UD  -> WriteEvictFull ", Xact::CacheStates::UD , false)
                ->Leaf("### C.12.5.4. UDP -> WriteEvictFull ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.12.5.5. SC  -> WriteEvictFull ", Xact::CacheStates::SC , false)
                ->Leaf("### C.12.5.6. SD  -> WriteEvictFull ", Xact::CacheStates::SD , false)
                ->Leaf("### C.12.5.7. I   -> WriteEvictFull ", Xact::CacheStates::I  , false)
            ->Rest()

        ->End();
        
    tcptInitial
        ->ForkREQ("# TCPt C.13. Initial state of WriteEvictOrEvict", Opcodes::REQ::WriteEvictOrEvict)

            ->ForkSilentTransitions("## C.13.1. Silent transitions: (Eviction = 0, Sharing = 0, Store = 0, Invalidation = 0)", false, false, false, false)
                ->Leaf("### C.13.1.1. UC  -> WriteEvictOrEvict ", Xact::CacheStates::UC , true )
                ->Leaf("### C.13.1.2. UCE -> WriteEvictOrEvict ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.13.1.3. UD  -> WriteEvictOrEvict ", Xact::CacheStates::UD , false)
                ->Leaf("### C.13.1.4. UDP -> WriteEvictOrEvict ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.13.1.5. SC  -> WriteEvictOrEvict ", Xact::CacheStates::SC , true )
                ->Leaf("### C.13.1.6. SD  -> WriteEvictOrEvict ", Xact::CacheStates::SD , false)
                ->Leaf("### C.13.1.7. I   -> WriteEvictOrEvict ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.13.2. Silent transitions: (Eviction = 0, Sharing = 0, Store = 1, Invalidation = 0)", false, false, true, false)
                ->Leaf("### C.13.2.1. UC  -> WriteEvictOrEvict ", Xact::CacheStates::UC , true )
                ->Leaf("### C.13.2.2. UCE -> WriteEvictOrEvict ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.13.2.3. UD  -> WriteEvictOrEvict ", Xact::CacheStates::UD , false)
                ->Leaf("### C.13.2.4. UDP -> WriteEvictOrEvict ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.13.2.5. SC  -> WriteEvictOrEvict ", Xact::CacheStates::SC , true )
                ->Leaf("### C.13.2.6. SD  -> WriteEvictOrEvict ", Xact::CacheStates::SD , false)
                ->Leaf("### C.13.2.7. I   -> WriteEvictOrEvict ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.13.3. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 0)", true, false, true, false)
                ->Leaf("### C.13.3.1. UC  -> WriteEvictOrEvict ", Xact::CacheStates::UC , true )
                ->Leaf("### C.13.3.2. UCE -> WriteEvictOrEvict ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.13.3.3. UD  -> WriteEvictOrEvict ", Xact::CacheStates::UD , false)
                ->Leaf("### C.13.3.4. UDP -> WriteEvictOrEvict ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.13.3.5. SC  -> WriteEvictOrEvict ", Xact::CacheStates::SC , true )
                ->Leaf("### C.13.3.6. SD  -> WriteEvictOrEvict ", Xact::CacheStates::SD , false)
                ->Leaf("### C.13.3.7. I   -> WriteEvictOrEvict ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.13.4. Silent transitions: (Eviction = 1, Sharing = 0, Store = 1, Invalidation = 1)", true, false, true, true)
                ->Leaf("### C.13.4.1. UC  -> WriteEvictOrEvict ", Xact::CacheStates::UC , true )
                ->Leaf("### C.13.4.2. UCE -> WriteEvictOrEvict ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.13.4.3. UD  -> WriteEvictOrEvict ", Xact::CacheStates::UD , false)
                ->Leaf("### C.13.4.4. UDP -> WriteEvictOrEvict ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.13.4.5. SC  -> WriteEvictOrEvict ", Xact::CacheStates::SC , true )
                ->Leaf("### C.13.4.6. SD  -> WriteEvictOrEvict ", Xact::CacheStates::SD , false)
                ->Leaf("### C.13.4.7. I   -> WriteEvictOrEvict ", Xact::CacheStates::I  , false)
            ->Rest()

            ->ForkSilentTransitions("## C.13.5. Silent transitions: (Eviction = 1, Sharing = 1, Store = 1, Invalidation = 1)", true, true, true, true)
                ->Leaf("### C.13.5.1. UC  -> WriteEvictOrEvict ", Xact::CacheStates::UC , true )
                ->Leaf("### C.13.5.2. UCE -> WriteEvictOrEvict ", Xact::CacheStates::UCE, false)
                ->Leaf("### C.13.5.3. UD  -> WriteEvictOrEvict ", Xact::CacheStates::UD , false)
                ->Leaf("### C.13.5.4. UDP -> WriteEvictOrEvict ", Xact::CacheStates::UDP, false)
                ->Leaf("### C.13.5.5. SC  -> WriteEvictOrEvict ", Xact::CacheStates::SC , true )
                ->Leaf("### C.13.5.6. SD  -> WriteEvictOrEvict ", Xact::CacheStates::SD , false)
                ->Leaf("### C.13.5.7. I   -> WriteEvictOrEvict ", Xact::CacheStates::I  , false)
            ->Rest()

        ->End();

    // TODO

    tcptInitial->End();
    tcptInitial = nullptr;
}

#endif
